export interface DashboardTopbarTemplate {
  key: string;
  name: string;
  category: 'Compact' | 'Search-First' | 'Command-Bar' | 'Minimal' | 'Enterprise' | 'Glass';
  style:
    | 'compact'
    | 'search_first'
    | 'breadcrumbs'
    | 'command_bar'
    | 'minimal'
    | 'enterprise'
    | 'floating'
    | 'glass';
  hasQuickSearch: boolean;
  hasBreadcrumbs: boolean;
  hasNotifications: boolean;
  hasUserMenu: boolean;
  hasAuditStreamTrigger: boolean;
  description: string;
}

export interface DashboardSidebarTemplate {
  key: string;
  name: string;
  category: 'Classic' | 'Compact' | 'Icon-Rail' | 'Dual' | 'Grouped' | 'Minimal' | 'Floating' | 'Enterprise' | 'Glass' | string;
  style:
    | 'classic'
    | 'compact'
    | 'floating'
    | 'icon_rail'
    | 'dual_sidebar'
    | 'grouped'
    | 'minimal'
    | 'enterprise'
    | 'rounded'
    | 'glass';
  collapsible: boolean;
  defaultCollapsed: boolean;
  showSectionHeaders: boolean;
  showRoleBadge: boolean;
  showQuickStatCards: boolean;
  width: string;
  description: string;
}

export interface DashboardShellTemplate {
  key: string;
  name: string;
  shellType: 'dashboard' | 'portal';
  topbarKey: string;
  sidebarKey: string;
  contentPadding: string;
  pageBackground: string;
  description: string;
}

export const DASHBOARD_TOPBAR_TEMPLATES: DashboardTopbarTemplate[] = [
  {
    key: 'dash-topbar-command-bar',
    name: 'Command Bar (Ctrl+K) Topbar',
    category: 'Command-Bar',
    style: 'command_bar',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Prominent central command bar with keyboard shortcut pill, live notifications, and audit feed.',
  },
  {
    key: 'dash-topbar-compact',
    name: 'Ultra-Compact Utility Bar',
    category: 'Compact',
    style: 'compact',
    hasQuickSearch: false,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Low-profile 48px height maximizing vertical screen real estate for data tables.',
  },
  {
    key: 'dash-topbar-search-first',
    name: 'Search-First Brokerage Bar',
    category: 'Search-First',
    style: 'search_first',
    hasQuickSearch: true,
    hasBreadcrumbs: false,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Full-width search input prioritizing customer, property, and invoice lookups.',
  },
  {
    key: 'dash-topbar-breadcrumbs-heavy',
    name: 'Deep Hierarchical Breadcrumbs',
    category: 'Enterprise',
    style: 'breadcrumbs',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Prominent multi-level navigation path with clickable parents and page title.',
  },
  {
    key: 'dash-topbar-floating-glass',
    name: 'Floating Glass Island Bar',
    category: 'Glass',
    style: 'floating',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Suspended rounded card with frosted backdrop blur resting above dashboard content.',
  },
  {
    key: 'dash-topbar-enterprise-split',
    name: 'Enterprise Dual Action Header',
    category: 'Enterprise',
    style: 'enterprise',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Comprehensive enterprise bar with environment badges, role chips, and audit feed.',
  },
  {
    key: 'dash-topbar-minimal-clean',
    name: 'Minimal Clean Header',
    category: 'Minimal',
    style: 'minimal',
    hasQuickSearch: false,
    hasBreadcrumbs: false,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Distraction-free topbar presenting only essential user profile actions.',
  },
  {
    key: 'dash-topbar-portal-customer',
    name: 'Customer Portal VIP Header',
    category: 'Glass',
    style: 'glass',
    hasQuickSearch: false,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Warm luxury header for verified buyers showing active deal count and advisor hotline.',
  },
  {
    key: 'dash-topbar-high-contrast',
    name: 'AAA High-Contrast Bar',
    category: 'Enterprise',
    style: 'compact',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Sharp black and lime border treatment for high accessibility compliance.',
  },
  {
    key: 'dash-topbar-cyber-midnight',
    name: 'Cyberpunk Neon Command Bar',
    category: 'Command-Bar',
    style: 'command_bar',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Dark midnight background with magenta accent lines and monospace status indicators.',
  },
  {
    key: 'dash-topbar-scandinavian',
    name: 'Nordic Clean Pale Topbar',
    category: 'Minimal',
    style: 'minimal',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Light birch undertones with gentle rounded controls and calm spacing.',
  },
  {
    key: 'dash-topbar-editorial-broadside',
    name: 'Editorial Serif Topbar',
    category: 'Enterprise',
    style: 'breadcrumbs',
    hasQuickSearch: false,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Serif typographic emphasis with gold accent status pips.',
  },
  {
    key: 'dash-topbar-urban-loft',
    name: 'Urban Loft Graphite Bar',
    category: 'Enterprise',
    style: 'compact',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Industrial slate concrete appearance with amber active badges.',
  },
  {
    key: 'dash-topbar-soft-pearl',
    name: 'Frosted Pearl Glass Bar',
    category: 'Glass',
    style: 'glass',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Translucent frosted glass with soft rounded search capsule.',
  },
  {
    key: 'dash-topbar-monochrome-stark',
    name: 'Stark Monochrome 50-Shades Bar',
    category: 'Minimal',
    style: 'minimal',
    hasQuickSearch: true,
    hasBreadcrumbs: false,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Pure neutral zinc grayscale palette with 1px border lines.',
  },
  {
    key: 'dash-topbar-saas-indigo',
    name: 'Silicon Valley PropTech Bar',
    category: 'Command-Bar',
    style: 'command_bar',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Indigo highlight accents with active environment pill and quick lead creation modal.',
  },
  {
    key: 'dash-topbar-art-deco',
    name: 'Manhattan Deco Topbar',
    category: 'Enterprise',
    style: 'breadcrumbs',
    hasQuickSearch: false,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Deep emerald with brass geometric accents and Cinzel typography.',
  },
  {
    key: 'dash-topbar-zen-charcoal',
    name: 'Kyoto Zen Charcoal Bar',
    category: 'Minimal',
    style: 'minimal',
    hasQuickSearch: false,
    hasBreadcrumbs: true,
    hasNotifications: false,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Spacious charcoal wabi-sabi background with tranquil spacing.',
  },
  {
    key: 'dash-topbar-dense-analyst',
    name: 'Dense Financial Analyst Bar',
    category: 'Compact',
    style: 'compact',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'High-density bar housing currency switcher, deal count badges, and export actions.',
  },
  {
    key: 'dash-topbar-resort-hospitality',
    name: 'Travertine Hospitality Topbar',
    category: 'Glass',
    style: 'glass',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Limestone beige surfaces with espresso typography and relaxed pacing.',
  },
  {
    key: 'dash-topbar-wireframe-blueprint',
    name: 'Architectural Blueprint Bar',
    category: 'Enterprise',
    style: 'breadcrumbs',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Drafting grid lines and monospace GPS coordinates for master-planned communities.',
  },
  {
    key: 'dash-topbar-floating-pill-capsule',
    name: 'Suspended Pill Command Bar',
    category: 'Glass',
    style: 'floating',
    hasQuickSearch: true,
    hasBreadcrumbs: false,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Floating pill with integrated quick search and user profile avatar.',
  },
  {
    key: 'dash-topbar-terracotta-warmth',
    name: 'Riviera Terracotta Topbar',
    category: 'Minimal',
    style: 'minimal',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Warm linen background with terracotta accents and Playfair Display headings.',
  },
  {
    key: 'dash-topbar-high-rise-leasing',
    name: 'High-Rise Commercial Header',
    category: 'Enterprise',
    style: 'enterprise',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: true,
    description: 'Displays active commercial floor occupancy rate and total square footage leased.',
  },
  {
    key: 'dash-topbar-brutalist-block',
    name: 'Neo-Brutalist Block Bar',
    category: 'Enterprise',
    style: 'compact',
    hasQuickSearch: true,
    hasBreadcrumbs: true,
    hasNotifications: true,
    hasUserMenu: true,
    hasAuditStreamTrigger: false,
    description: 'Thick 2px solid black border with yellow badge accents and hard drop shadows.',
  },
];

export const DASHBOARD_SIDEBAR_TEMPLATES: DashboardSidebarTemplate[] = [
  {
    key: 'dash-sidebar-classic-grouped',
    name: 'Classic Grouped Enterprise Sidebar',
    category: 'Grouped',
    style: 'grouped',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: true,
    width: '260px',
    description: 'Industry-standard grouped sidebar with collapsible category headers and role badge.',
  },
  {
    key: 'dash-sidebar-compact-rail',
    name: 'Slim Icon Rail Sidebar',
    category: 'Icon-Rail',
    style: 'icon_rail',
    collapsible: false,
    defaultCollapsed: true,
    showSectionHeaders: false,
    showRoleBadge: false,
    showQuickStatCards: false,
    width: '72px',
    description: 'Compact 72px rail displaying high-contrast icons with hover tooltips.',
  },
  {
    key: 'dash-sidebar-floating-glass',
    name: 'Floating Glass Panel Sidebar',
    category: 'Floating',
    style: 'floating',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: false,
    width: '270px',
    description: 'Suspended card with rounded corners resting 16px off the viewport edge.',
  },
  {
    key: 'dash-sidebar-dual-flyout',
    name: 'Dual Rail + Expandable Flyout',
    category: 'Dual',
    style: 'dual_sidebar',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: true,
    width: '320px',
    description: 'Primary module rail on left with secondary sub-navigation drawer on right.',
  },
  {
    key: 'dash-sidebar-minimal-clean',
    name: 'Minimalist Clean Slate',
    category: 'Minimal',
    style: 'minimal',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: false,
    showRoleBadge: false,
    showQuickStatCards: false,
    width: '240px',
    description: 'Understated single-tone sidebar without heavy cards or distractions.',
  },
  {
    key: 'dash-sidebar-enterprise-dark',
    name: 'Obsidian Gold Executive Sidebar',
    category: 'Enterprise',
    style: 'enterprise',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: true,
    width: '280px',
    description: 'Deep black background with gold border accents and executive revenue counters.',
  },
  {
    key: 'dash-sidebar-portal-customer',
    name: 'Customer VIP Portal Sidebar',
    category: 'Classic',
    style: 'classic',
    collapsible: false,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: false,
    width: '250px',
    description: 'Tailored for verified buyers: My Deals, Invoices, Payments, and Private Documents.',
  },
  {
    key: 'dash-sidebar-high-contrast',
    name: 'AAA High-Contrast Black & Lime',
    category: 'Classic',
    style: 'classic',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: false,
    width: '260px',
    description: 'Sharp solid borders with neon lime focus indicators for maximum accessibility.',
  },
  {
    key: 'dash-sidebar-cyber-neon',
    name: 'Cyberpunk Midnight Neon Rail',
    category: 'Icon-Rail',
    style: 'icon_rail',
    collapsible: false,
    defaultCollapsed: true,
    showSectionHeaders: false,
    showRoleBadge: false,
    showQuickStatCards: false,
    width: '76px',
    description: 'Dark midnight background with glowing magenta active item borders.',
  },
  {
    key: 'dash-sidebar-scandinavian',
    name: 'Nordic Birch Minimal Sidebar',
    category: 'Minimal',
    style: 'rounded',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: false,
    showQuickStatCards: false,
    width: '250px',
    description: 'Warm pale wood undertones with pill-shaped active navigation links.',
  },
  {
    key: 'dash-sidebar-editorial-manor',
    name: 'Editorial Serif Manor Sidebar',
    category: 'Classic',
    style: 'classic',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: false,
    width: '270px',
    description: 'Refined serif typography with delicate hairline dividers.',
  },
  {
    key: 'dash-sidebar-urban-graphite',
    name: 'Metropolitan Loft Graphite Sidebar',
    category: 'Grouped',
    style: 'grouped',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: true,
    width: '265px',
    description: 'Concrete industrial slate with amber notification badges.',
  },
  {
    key: 'dash-sidebar-frosted-pearl',
    name: 'Frosted Crystal Glass Sidebar',
    category: 'Floating',
    style: 'glass',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: false,
    showQuickStatCards: false,
    width: '260px',
    description: 'Translucent frosted glass with soft rounded pill links and mint highlights.',
  },
  {
    key: 'dash-sidebar-monochrome-stark',
    name: 'Stark Monochrome Zinc Sidebar',
    category: 'Minimal',
    style: 'minimal',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: false,
    width: '240px',
    description: 'Pure neutral zinc grayscale palette with 1px border lines.',
  },
  {
    key: 'dash-sidebar-saas-indigo',
    name: 'Silicon Valley PropTech Sidebar',
    category: 'Grouped',
    style: 'grouped',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: true,
    width: '260px',
    description: 'Indigo active items with integrated quick-add shortcuts.',
  },
  {
    key: 'dash-sidebar-art-deco',
    name: 'Manhattan Deco Emerald Sidebar',
    category: 'Classic',
    style: 'classic',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: false,
    width: '275px',
    description: 'Deep emerald with polished brass geometric borders and Cinzel serif.',
  },
  {
    key: 'dash-sidebar-zen-charcoal',
    name: 'Kyoto Zen Charcoal Sidebar',
    category: 'Minimal',
    style: 'minimal',
    collapsible: false,
    defaultCollapsed: false,
    showSectionHeaders: false,
    showRoleBadge: false,
    showQuickStatCards: false,
    width: '230px',
    description: 'Tranquil wabi-sabi charcoal layout celebrating negative space.',
  },
  {
    key: 'dash-sidebar-dense-metrics',
    name: 'High-Density Portfolio Sidebar',
    category: 'Enterprise',
    style: 'enterprise',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: true,
    width: '280px',
    description: 'Includes mini-sparkline property inventory and collection metrics.',
  },
  {
    key: 'dash-sidebar-travertine-resort',
    name: 'Travertine Hospitality Sidebar',
    category: 'Classic',
    style: 'classic',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: false,
    width: '260px',
    description: 'Limestone beige surfaces with espresso typography evoking 5-star concierge.',
  },
  {
    key: 'dash-sidebar-wireframe-blueprint',
    name: 'Architectural Blueprint Sidebar',
    category: 'Enterprise',
    style: 'enterprise',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: false,
    width: '265px',
    description: 'Drafting grid lines and monospace technical specifications.',
  },
  {
    key: 'dash-sidebar-floating-pill',
    name: 'Floating Rounded Pill Sidebar',
    category: 'Floating',
    style: 'rounded',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: false,
    showRoleBadge: true,
    showQuickStatCards: false,
    width: '255px',
    description: 'Floating rounded pill navigation with soft shadow elevation.',
  },
  {
    key: 'dash-sidebar-terracotta-warmth',
    name: 'Riviera Terracotta Sidebar',
    category: 'Classic',
    style: 'classic',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: false,
    width: '260px',
    description: 'Warm linen background with terracotta accents and Playfair Display headings.',
  },
  {
    key: 'dash-sidebar-commercial-leasing',
    name: 'Commercial Leasing & Investor Sidebar',
    category: 'Enterprise',
    style: 'enterprise',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: true,
    width: '285px',
    description: 'Dedicated to institutional real estate trusts, lease disclosures, and investor relations.',
  },
  {
    key: 'dash-sidebar-brutalist-block',
    name: 'Neo-Brutalist Heavy Sidebar',
    category: 'Classic',
    style: 'classic',
    collapsible: false,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: false,
    showQuickStatCards: false,
    width: '250px',
    description: 'Thick 2px solid black borders, neo-brutalist hard drop shadows, and zero border radius.',
  },
  {
    key: 'dash-sidebar-soft-neumorphic',
    name: 'Soft Neumorphic Card Sidebar',
    category: 'Floating',
    style: 'rounded',
    collapsible: true,
    defaultCollapsed: false,
    showSectionHeaders: true,
    showRoleBadge: true,
    showQuickStatCards: false,
    width: '260px',
    description: 'Subtle dual-shadow neumorphic embossed cards with gentle elevation.',
  },
];

export const DASHBOARD_SHELL_TEMPLATES: DashboardShellTemplate[] = [
  {
    key: 'shell-standard-enterprise',
    name: 'Standard Enterprise Workspace',
    shellType: 'dashboard',
    topbarKey: 'dash-topbar-command-bar',
    sidebarKey: 'dash-sidebar-classic-grouped',
    contentPadding: '1.5rem',
    pageBackground: 'var(--background)',
    description: 'Default executive workspace balancing visibility and density.',
  },
  {
    key: 'shell-compact-analyst',
    name: 'Compact Data Analyst Workspace',
    shellType: 'dashboard',
    topbarKey: 'dash-topbar-compact',
    sidebarKey: 'dash-sidebar-compact-rail',
    contentPadding: '1rem',
    pageBackground: 'var(--background)',
    description: 'Maximizes usable viewport width and height for expansive data tables.',
  },
  {
    key: 'shell-floating-glass',
    name: 'Floating Glass Modern Shell',
    shellType: 'dashboard',
    topbarKey: 'dash-topbar-floating-glass',
    sidebarKey: 'dash-sidebar-floating-glass',
    contentPadding: '2rem',
    pageBackground: 'var(--background)',
    description: 'Luxury floating aesthetic with suspended frosted glass panels.',
  },
  {
    key: 'shell-customer-portal',
    name: 'Customer Portal VIP Shell',
    shellType: 'portal',
    topbarKey: 'dash-topbar-portal-customer',
    sidebarKey: 'dash-sidebar-portal-customer',
    contentPadding: '2rem',
    pageBackground: 'var(--background)',
    description: 'Clean luxury layout for verified buyers, tenants, and clients.',
  },
  {
    key: 'shell-portal-investor',
    name: 'Institutional Investor Terminal Shell',
    shellType: 'portal',
    topbarKey: 'dash-topbar-portal-customer',
    sidebarKey: 'dash-sidebar-portal-customer',
    contentPadding: '1.5rem',
    pageBackground: 'var(--background)',
    description: 'High-density metrics and yield breakdown terminal for institutional investment funds.',
  },
];

export function getDashboardTopbarByKey(key: string): DashboardTopbarTemplate {
  return DASHBOARD_TOPBAR_TEMPLATES.find((t) => t.key === key) || DASHBOARD_TOPBAR_TEMPLATES[0];
}

export function getDashboardSidebarByKey(key: string): DashboardSidebarTemplate {
  return DASHBOARD_SIDEBAR_TEMPLATES.find((s) => s.key === key) || DASHBOARD_SIDEBAR_TEMPLATES[0];
}

export function getDashboardShellByKey(key: string): DashboardShellTemplate {
  return DASHBOARD_SHELL_TEMPLATES.find((s) => s.key === key) || DASHBOARD_SHELL_TEMPLATES[0];
}
