export interface HoverEffectDefinition {
  key: string;
  name: string;
  category: 'Transform' | 'Color' | 'Border' | 'Media' | 'Glow' | 'Interactive' | string;
  cssClass: string;
  hardwareAccelerated: boolean;
  reducedMotionFallback: string;
  description: string;
}

export const HOVER_EFFECT_REGISTRY: HoverEffectDefinition[] = [
  {
    key: 'hover-lift-subtle',
    name: 'Subtle Card Lift (Y -4px)',
    category: 'Transform',
    cssClass: 'hover:-translate-y-1 hover:shadow-lg transition-transform duration-200',
    hardwareAccelerated: true,
    reducedMotionFallback: 'hover:shadow-md',
    description: 'Elevates card vertically by 4px with increased shadow depth.',
  },
  {
    key: 'hover-lift-dramatic',
    name: 'Dramatic Penthouse Lift (Y -8px)',
    category: 'Transform',
    cssClass: 'hover:-translate-y-2 hover:shadow-2xl transition-all duration-300',
    hardwareAccelerated: true,
    reducedMotionFallback: 'hover:shadow-lg',
    description: 'Noticeable 8px elevation with deep drop shadow for luxury featured villas.',
  },
  {
    key: 'hover-scale-gentle',
    name: 'Gentle Scale (102%)',
    category: 'Transform',
    cssClass: 'hover:scale-[1.02] transition-transform duration-200',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Subtle 2% scale increase providing responsive tactile feedback.',
  },
  {
    key: 'hover-image-zoom',
    name: 'Inner Image Zoom (105%)',
    category: 'Media',
    cssClass: 'group-hover:scale-105 transition-transform duration-500 ease-out',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Zooms property photography inside an overflow-hidden container.',
  },
  {
    key: 'hover-underline-slide',
    name: 'Underline Left-to-Right Slide',
    category: 'Border',
    cssClass: 'relative after:absolute after:bottom-0 after:left-0 after:h-[2px] after:w-0 hover:after:w-full after:transition-all after:duration-300',
    hardwareAccelerated: false,
    reducedMotionFallback: 'hover:underline',
    description: 'Draws an architectural highlight line from left to right beneath text.',
  },
  {
    key: 'hover-border-draw',
    name: 'Border Accent Draw',
    category: 'Border',
    cssClass: 'hover:border-[var(--primary)] transition-colors duration-200',
    hardwareAccelerated: false,
    reducedMotionFallback: 'hover:border-[var(--primary)]',
    description: 'Transitions subtle 10% border to solid brand primary color on hover.',
  },
  {
    key: 'hover-background-fill',
    name: 'Background Solid Fill',
    category: 'Color',
    cssClass: 'hover:bg-[var(--primary)] hover:text-[var(--primary-foreground)] transition-colors duration-200',
    hardwareAccelerated: false,
    reducedMotionFallback: 'hover:bg-[var(--primary)]',
    description: 'Fills ghost/outline buttons with vibrant primary brand color.',
  },
  {
    key: 'hover-arrow-shift',
    name: 'Right Arrow Horizontal Shift',
    category: 'Transform',
    cssClass: 'group-hover:translate-x-1.5 transition-transform duration-200',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Nudges CTA chevron arrow forward by 6px on hover.',
  },
  {
    key: 'hover-glow-ambient',
    name: 'Ambient Primary Brand Glow',
    category: 'Glow',
    cssClass: 'hover:shadow-[0_0_25px_rgba(59,130,246,0.35)] transition-shadow duration-300',
    hardwareAccelerated: false,
    reducedMotionFallback: 'none',
    description: 'Casts a soft colored ambient halo around interactive buttons.',
  },
  {
    key: 'hover-spotlight-radial',
    name: 'Radial Cursor Spotlight',
    category: 'Glow',
    cssClass: 'hover:before:opacity-100 transition-opacity duration-300',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Reveals a localized radial spotlight following cursor position.',
  },
  {
    key: 'hover-3d-tilt',
    name: 'Perspective 3D Tilt',
    category: 'Interactive',
    cssClass: 'hover:rotate-x-2 hover:rotate-y-2 transition-transform duration-200',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Subtle tilt in 3D perspective based on pointer displacement.',
  },
  {
    key: 'hover-soft-rotate',
    name: 'Micro Rotate (+2 Deg)',
    category: 'Transform',
    cssClass: 'hover:rotate-1 transition-transform duration-150',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Playful micro rotation giving badges and tags a tactile physical feel.',
  },
  {
    key: 'hover-magnetic',
    name: 'Magnetic Cursor Pull',
    category: 'Interactive',
    cssClass: 'transition-transform duration-150',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Pulls button center slightly toward cursor pointer.',
  },
  {
    key: 'hover-gradient-shift',
    name: 'Linear Gradient Hue Shift',
    category: 'Color',
    cssClass: 'hover:bg-gradient-to-r hover:from-amber-400 hover:to-amber-600 transition-all duration-300',
    hardwareAccelerated: false,
    reducedMotionFallback: 'none',
    description: 'Shifts angle and saturation of gold metallic gradients.',
  },
  {
    key: 'hover-image-pan',
    name: 'Horizontal Architectural Pan',
    category: 'Media',
    cssClass: 'group-hover:-translate-x-2 transition-transform duration-700 ease-out',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Subtle panoramic panning movement on wide villa living room photography.',
  },
  {
    key: 'hover-shadow-rise',
    name: 'Floating Shadow Expansion',
    category: 'Transform',
    cssClass: 'hover:shadow-2xl transition-shadow duration-300',
    hardwareAccelerated: false,
    reducedMotionFallback: 'none',
    description: 'Expands blur radius of shadow without translating element geometry.',
  },
  {
    key: 'hover-text-swap',
    name: 'Vertical Text Marquee Swap',
    category: 'Transform',
    cssClass: 'overflow-hidden group-hover:-translate-y-full transition-transform duration-200',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Rolls default label upwards to reveal secondary state message underneath.',
  },
  {
    key: 'hover-reveal-overlay',
    name: 'Dark Glass Detail Overlay Reveal',
    category: 'Media',
    cssClass: 'opacity-0 group-hover:opacity-100 transition-opacity duration-300',
    hardwareAccelerated: true,
    reducedMotionFallback: 'opacity-100',
    description: 'Fades in specs overlay (Bedrooms, Bathrooms, SqFt) over listing card image.',
  },
  {
    key: 'hover-gold-shimmer',
    name: '24K Gold Shimmer Sweep',
    category: 'Glow',
    cssClass: 'hover:brightness-110 transition-all duration-200',
    hardwareAccelerated: false,
    reducedMotionFallback: 'none',
    description: 'Brief metallic luminance sweep across luxury buttons.',
  },
  {
    key: 'hover-corner-accent',
    name: 'Architectural Corner L-Markers',
    category: 'Border',
    cssClass: 'group-hover:border-[var(--primary)] transition-all duration-200',
    hardwareAccelerated: false,
    reducedMotionFallback: 'none',
    description: 'Highlights 4 corner geometric drafting markers on technical blueprints.',
  },
  {
    key: 'hover-card-invert',
    name: 'Inverted High-Contrast Flip',
    category: 'Color',
    cssClass: 'hover:bg-white hover:text-black transition-colors duration-200',
    hardwareAccelerated: false,
    reducedMotionFallback: 'none',
    description: 'Inverts background and foreground colors for stark brutalist styling.',
  },
  {
    key: 'hover-button-expand',
    name: 'Pill Width Expansion (+12px)',
    category: 'Transform',
    cssClass: 'hover:px-6 transition-all duration-200',
    hardwareAccelerated: false,
    reducedMotionFallback: 'none',
    description: 'Expands horizontal padding for clear affirmative hover indication.',
  },
  {
    key: 'hover-blur-dim-siblings',
    name: 'Focus Blur on Siblings',
    category: 'Interactive',
    cssClass: 'group-hover:opacity-50 hover:!opacity-100 transition-opacity duration-200',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Dims neighboring cards in a grid to draw pure focus to the hovered item.',
  },
  {
    key: 'hover-badge-bounce',
    name: 'Micro Badge Spring Bounce',
    category: 'Transform',
    cssClass: 'group-hover:-translate-y-1 transition-transform duration-150',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Subtle spring bounce for price tags and availability badges.',
  },
  {
    key: 'hover-monogram-spin',
    name: 'Quarter Turn Monogram (90 Deg)',
    category: 'Transform',
    cssClass: 'group-hover:rotate-90 transition-transform duration-300 ease-out',
    hardwareAccelerated: true,
    reducedMotionFallback: 'none',
    description: 'Rotates architectural crosshair icon by 90 degrees.',
  },
];

export function getHoverEffectByKey(key: string): HoverEffectDefinition {
  return HOVER_EFFECT_REGISTRY.find((h) => h.key === key) || HOVER_EFFECT_REGISTRY[0];
}
