export interface MobileNavTemplate {
  key: string;
  name: string;
  category: 'Drawer' | 'Full-Screen' | 'Bottom-Dock' | 'Sheet' | 'Minimal' | string;
  pattern:
    | 'drawer_left'
    | 'drawer_right'
    | 'full_curtain'
    | 'bottom_dock'
    | 'accordion_sheet'
    | 'top_drop_tray'
    | 'floating_island';
  blurOverlay: boolean;
  quickContactBar: boolean;
  animationType: 'slide' | 'fade' | 'curtain' | 'spring' | 'expand';
  description: string;
}

export const MOBILE_NAV_TEMPLATES: MobileNavTemplate[] = [
  {
    key: 'mob-drawer-left',
    name: 'Classic Slide Drawer Left',
    category: 'Drawer',
    pattern: 'drawer_left',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'slide',
    description: 'Smooth sliding drawer emerging from the left with dark backdrop blur and contact links.',
  },
  {
    key: 'mob-drawer-right',
    name: 'Executive Slide Drawer Right',
    category: 'Drawer',
    pattern: 'drawer_right',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'slide',
    description: 'Sleek right-side drawer prioritizing client login and direct concierge WhatsApp buttons.',
  },
  {
    key: 'mob-full-curtain',
    name: 'Grand Full-Screen Curtain Takeover',
    category: 'Full-Screen',
    pattern: 'full_curtain',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'curtain',
    description: 'Immersive full-screen dramatic takeover with staggered luxury typography reveals.',
  },
  {
    key: 'mob-bottom-dock',
    name: 'iOS Floating Bottom Dock',
    category: 'Bottom-Dock',
    pattern: 'bottom_dock',
    blurOverlay: true,
    quickContactBar: false,
    animationType: 'spring',
    description: 'Thumb-friendly floating bottom dock housing 4 core tabs and central action button.',
  },
  {
    key: 'mob-accordion-sheet',
    name: 'Bottom Accordion Sheet',
    category: 'Sheet',
    pattern: 'accordion_sheet',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'slide',
    description: 'Pulls up from the bottom with expandable nested property types and neighborhoods.',
  },
  {
    key: 'mob-top-drop-tray',
    name: 'Header Expanding Tray',
    category: 'Minimal',
    pattern: 'top_drop_tray',
    blurOverlay: false,
    quickContactBar: false,
    animationType: 'expand',
    description: 'Smooth downward expansion originating from underneath the active header.',
  },
  {
    key: 'mob-floating-island',
    name: 'Suspended Glass Island',
    category: 'Minimal',
    pattern: 'floating_island',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'fade',
    description: 'Centered rounded modal card with frosted glass borders and glowing brand monogram.',
  },
  {
    key: 'mob-editorial-curtain',
    name: 'Editorial Serif Broadside',
    category: 'Full-Screen',
    pattern: 'full_curtain',
    blurOverlay: false,
    quickContactBar: true,
    animationType: 'curtain',
    description: 'Parchment background with prominent serif chapter links and concierge address.',
  },
  {
    key: 'mob-brutalist-stack',
    name: 'Neo-Brutalist Card Drawer',
    category: 'Drawer',
    pattern: 'drawer_left',
    blurOverlay: false,
    quickContactBar: false,
    animationType: 'slide',
    description: 'Stark black borders with bold yellow accent cards and hard drop shadows.',
  },
  {
    key: 'mob-dark-matrix',
    name: 'Cyberpunk Neon Drawer',
    category: 'Drawer',
    pattern: 'drawer_right',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'slide',
    description: 'Pitch dark backdrop with neon magenta divider lines and monospace indicators.',
  },
  {
    key: 'mob-luxury-split-curtain',
    name: 'Split Tone Luxury Curtain',
    category: 'Full-Screen',
    pattern: 'full_curtain',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'curtain',
    description: 'Two-tone split screen with active 3D villa preview above and navigation links below.',
  },
  {
    key: 'mob-bottom-bar-compact',
    name: 'Compact Bottom Navigation Strip',
    category: 'Bottom-Dock',
    pattern: 'bottom_dock',
    blurOverlay: false,
    quickContactBar: false,
    animationType: 'fade',
    description: 'Fixed bottom bar with icon labels for Home, Listings, 3D, and Concierge.',
  },
  {
    key: 'mob-soft-glass-drawer',
    name: 'Frosted Crystal Drawer',
    category: 'Drawer',
    pattern: 'drawer_left',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'slide',
    description: 'Translucent frosted drawer with soft rounded pill links and mint green highlights.',
  },
  {
    key: 'mob-staggered-minimal',
    name: 'Ultra-Minimal Staggered Menu',
    category: 'Full-Screen',
    pattern: 'full_curtain',
    blurOverlay: true,
    quickContactBar: false,
    animationType: 'spring',
    description: 'Large clean typography centered on the screen with subtle micro-animations.',
  },
  {
    key: 'mob-corporate-sheet',
    name: 'Corporate Executive Sheet',
    category: 'Sheet',
    pattern: 'accordion_sheet',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'slide',
    description: 'Bottom sheet presenting property divisions, investment disclosures, and contact lines.',
  },
  {
    key: 'mob-terracotta-curtain',
    name: 'Mediterranean Sun Curtain',
    category: 'Full-Screen',
    pattern: 'full_curtain',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'curtain',
    description: 'Warm terracotta palette with large Playfair Display navigation links.',
  },
  {
    key: 'mob-high-contrast-drawer',
    name: 'High-Contrast Technical Drawer',
    category: 'Drawer',
    pattern: 'drawer_left',
    blurOverlay: false,
    quickContactBar: true,
    animationType: 'slide',
    description: 'Solid black drawer with neon lime badges and high-contrast accessible touch targets.',
  },
  {
    key: 'mob-scandinavian-tray',
    name: 'Nordic Clean Drop Tray',
    category: 'Minimal',
    pattern: 'top_drop_tray',
    blurOverlay: true,
    quickContactBar: false,
    animationType: 'expand',
    description: 'Soft birch tones dropping smoothly from the header with rounded button pills.',
  },
  {
    key: 'mob-zen-charcoal',
    name: 'Kyoto Zen Charcoal Curtain',
    category: 'Full-Screen',
    pattern: 'full_curtain',
    blurOverlay: false,
    quickContactBar: true,
    animationType: 'fade',
    description: 'Spacious charcoal wabi-sabi background with tranquil vertical navigation flow.',
  },
  {
    key: 'mob-monochrome-drawer',
    name: 'Monochrome Pure Slate Drawer',
    category: 'Drawer',
    pattern: 'drawer_right',
    blurOverlay: true,
    quickContactBar: false,
    animationType: 'slide',
    description: 'Crisp black and white architectural menu with line-delimited items.',
  },
  {
    key: 'mob-art-deco-sheet',
    name: 'Gilded Deco Bottom Sheet',
    category: 'Sheet',
    pattern: 'accordion_sheet',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'slide',
    description: 'Emerald green background with brass geometric border accents and Cinzel serif.',
  },
  {
    key: 'mob-resort-warm-stone',
    name: 'Travertine Hospitality Drawer',
    category: 'Drawer',
    pattern: 'drawer_left',
    blurOverlay: true,
    quickContactBar: true,
    animationType: 'slide',
    description: 'Limestone beige surfaces with espresso typography evoking 5-star concierge services.',
  },
  {
    key: 'mob-commercial-dock',
    name: 'Skyline Commercial Dock',
    category: 'Bottom-Dock',
    pattern: 'bottom_dock',
    blurOverlay: false,
    quickContactBar: true,
    animationType: 'spring',
    description: 'Optimized for high-density multi-story office building browsing on mobile.',
  },
  {
    key: 'mob-floating-compact',
    name: 'Floating Pill Quick Menu',
    category: 'Minimal',
    pattern: 'floating_island',
    blurOverlay: true,
    quickContactBar: false,
    animationType: 'spring',
    description: 'Lightweight modal pill positioned near thumb reach for rapid property navigation.',
  },
  {
    key: 'mob-wireframe-loft',
    name: 'Urban Loft Wireframe Menu',
    category: 'Drawer',
    pattern: 'drawer_right',
    blurOverlay: false,
    quickContactBar: true,
    animationType: 'slide',
    description: 'Industrial slate drawer with technical monospace specs and blueprint lines.',
  },
];

export function getMobileNavTemplateByKey(key: string): MobileNavTemplate {
  return MOBILE_NAV_TEMPLATES.find((t) => t.key === key) || MOBILE_NAV_TEMPLATES[0];
}
