export interface PublicFooterTemplate {
  key: string;
  name: string;
  category: 'Editorial' | 'Luxury' | 'Minimal' | 'Corporate' | 'Architectural' | 'Interactive' | 'Warm' | string;
  layoutStyle:
    | 'multicolumn'
    | 'centered'
    | 'contact_card'
    | 'newsletter_hero'
    | 'split_manifesto'
    | 'partner_wall'
    | 'compact_inline';
  showNewsletter: boolean;
  showSocialIcons: boolean;
  showPartnerLogos: boolean;
  columnsCount: number;
  description: string;
}

export const PUBLIC_FOOTER_TEMPLATES: PublicFooterTemplate[] = [
  {
    key: 'footer-large-editorial',
    name: 'Large Editorial Broadsheet Footer',
    category: 'Editorial',
    layoutStyle: 'multicolumn',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: true,
    columnsCount: 4,
    description: 'Comprehensive 4-column footer with brand manifesto, newsletter subscription, and partner logos.',
  },
  {
    key: 'footer-minimal-centered',
    name: 'Minimal Centered Monogram',
    category: 'Minimal',
    layoutStyle: 'centered',
    showNewsletter: false,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 1,
    description: 'Understated single-column layout centered on architectural emblem, inline links, and legal notice.',
  },
  {
    key: 'footer-property-contact',
    name: 'Direct Concierge Contact Footer',
    category: 'Interactive',
    layoutStyle: 'contact_card',
    showNewsletter: false,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 3,
    description: 'Features interactive office address card, telephone concierge trigger, and WhatsApp line.',
  },
  {
    key: 'footer-newsletter-focused',
    name: 'VIP Newsletter Hero Footer',
    category: 'Corporate',
    layoutStyle: 'newsletter_hero',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: true,
    columnsCount: 3,
    description: 'Hero-sized newsletter subscription box for off-market penthouse notifications.',
  },
  {
    key: 'footer-dark-premium',
    name: 'Obsidian & Gold Premium Footer',
    category: 'Luxury',
    layoutStyle: 'multicolumn',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: true,
    columnsCount: 4,
    description: 'Deep black background with gold border accents and discreet legal disclosures.',
  },
  {
    key: 'footer-split-manifesto',
    name: 'Split Architectural Manifesto',
    category: 'Architectural',
    layoutStyle: 'split_manifesto',
    showNewsletter: false,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 2,
    description: '50/50 split layout featuring company architectural philosophy on left and navigation grid on right.',
  },
  {
    key: 'footer-partner-wall',
    name: 'Developer & Bank Partner Wall',
    category: 'Corporate',
    layoutStyle: 'partner_wall',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: true,
    columnsCount: 4,
    description: 'Prominent logo showcase grid of partnering international banks, architects, and engineering firms.',
  },
  {
    key: 'footer-compact-inline',
    name: 'Compact Horizontal Strip',
    category: 'Minimal',
    layoutStyle: 'compact_inline',
    showNewsletter: false,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 1,
    description: 'Ultra-thin single-row footer with copyright and inline legal links for fullscreen pages.',
  },
  {
    key: 'footer-brutalist-block',
    name: 'Neo-Brutalist Solid Footer',
    category: 'Architectural',
    layoutStyle: 'multicolumn',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 3,
    description: 'Stark black borders, high-contrast monospace links, and prominent zero-radius button.',
  },
  {
    key: 'footer-soft-glass',
    name: 'Frosted Crystal Footer',
    category: 'Minimal',
    layoutStyle: 'multicolumn',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 3,
    description: 'Translucent frosted backdrop-blur panel with soft glowing borders and mint highlights.',
  },
  {
    key: 'footer-terracotta-warm',
    name: 'Mediterranean Terracotta Courtyard',
    category: 'Luxury',
    layoutStyle: 'multicolumn',
    showNewsletter: false,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 3,
    description: 'Warm linen background with terracotta accents and Playfair Display headings.',
  },
  {
    key: 'footer-cyber-neon',
    name: 'Cyberpunk Midnight Footer',
    category: 'Interactive',
    layoutStyle: 'multicolumn',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: true,
    columnsCount: 4,
    description: 'Dark midnight blue with neon magenta accents and live network coordinate indicators.',
  },
  {
    key: 'footer-art-deco-emerald',
    name: 'Gilded Deco Emerald Footer',
    category: 'Luxury',
    layoutStyle: 'split_manifesto',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 2,
    description: 'Deep emerald background with polished brass geometric borders and Cinzel serif typography.',
  },
  {
    key: 'footer-travertine-resort',
    name: 'Travertine Resort Manor Footer',
    category: 'Luxury',
    layoutStyle: 'contact_card',
    showNewsletter: false,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 3,
    description: 'Warm limestone beige with espresso typography and relaxed luxury hospitality layout.',
  },
  {
    key: 'footer-high-contrast',
    name: 'AAA High-Contrast Black & Lime',
    category: 'Interactive',
    layoutStyle: 'multicolumn',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 3,
    description: 'Solid dark container with bright neon lime accents and accessible high-contrast links.',
  },
  {
    key: 'footer-scandinavian-light',
    name: 'Stockholm Light Birch Footer',
    category: 'Minimal',
    layoutStyle: 'multicolumn',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 4,
    description: 'Nordic pale wood tones and airy whitespace with rounded button pills.',
  },
  {
    key: 'footer-zen-charcoal',
    name: 'Kyoto Zen Charcoal Footer',
    category: 'Minimal',
    layoutStyle: 'centered',
    showNewsletter: false,
    showSocialIcons: false,
    showPartnerLogos: false,
    columnsCount: 1,
    description: 'Tranquil charcoal layout celebrating negative space, silence, and discreet contact.',
  },
  {
    key: 'footer-urban-loft',
    name: 'Metropolitan Loft Blueprint',
    category: 'Architectural',
    layoutStyle: 'multicolumn',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: true,
    columnsCount: 4,
    description: 'Industrial slate concrete with amber highlights and technical structural specifications.',
  },
  {
    key: 'footer-monochrome-slate',
    name: 'Pure Monochrome Slate 50-Shades',
    category: 'Minimal',
    layoutStyle: 'multicolumn',
    showNewsletter: false,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 3,
    description: 'Neutral zinc grayscale palette free of color distraction for architectural purists.',
  },
  {
    key: 'footer-saas-clean',
    name: 'Silicon Valley SaaS Footer',
    category: 'Corporate',
    layoutStyle: 'multicolumn',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: true,
    columnsCount: 5,
    description: 'High-density 5-column technical footer with platform status, docs, and API links.',
  },
  {
    key: 'footer-alpine-retreat',
    name: 'Alpine Forest Retreat Footer',
    category: 'Luxury',
    layoutStyle: 'multicolumn',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 3,
    description: 'Deep evergreen pine tones paired with warm botanical textures.',
  },
  {
    key: 'footer-contemporary-gold',
    name: 'Majestic Gilded Estate Footer',
    category: 'Luxury',
    layoutStyle: 'newsletter_hero',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: true,
    columnsCount: 4,
    description: '24-karat warm gold finishes and Cinzel serif branding for royal residential developments.',
  },
  {
    key: 'footer-desert-adobe',
    name: 'Sonoran Desert Modern Footer',
    category: 'Warm',
    layoutStyle: 'multicolumn',
    showNewsletter: false,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 3,
    description: 'Palm Springs desert sand, adobe sunset tones, and mid-century clean line layout.',
  },
  {
    key: 'footer-commercial-leasing',
    name: 'Commercial Leasing & Investor Footer',
    category: 'Corporate',
    layoutStyle: 'multicolumn',
    showNewsletter: true,
    showSocialIcons: true,
    showPartnerLogos: true,
    columnsCount: 4,
    description: 'Dedicated to institutional real estate trusts, lease disclosures, and investor relations.',
  },
  {
    key: 'footer-floating-capsule',
    name: 'Detached Floating Capsule Footer',
    category: 'Modern',
    layoutStyle: 'centered',
    showNewsletter: false,
    showSocialIcons: true,
    showPartnerLogos: false,
    columnsCount: 1,
    description: 'Suspended pill card resting above the bottom edge with soft frosted glass aesthetics.',
  },
];

export function getFooterTemplateByKey(key: string): PublicFooterTemplate {
  return PUBLIC_FOOTER_TEMPLATES.find((f) => f.key === key) || PUBLIC_FOOTER_TEMPLATES[0];
}
