export interface PublicTopbarTemplate {
  key: string;
  name: string;
  category: 'Minimal' | 'Luxury' | 'Editorial' | 'Architectural' | 'Modern' | 'Functional' | string;
  layoutStyle:
    | 'logo_left_nav_right'
    | 'logo_center_split_nav'
    | 'floating_pill'
    | 'double_row'
    | 'overlay_hero'
    | 'mega_menu'
    | 'search_first'
    | 'sidebar_trigger';
  sticky: boolean;
  backdropBlur: boolean;
  searchSlotEnabled: boolean;
  ctaButtonText?: string;
  ctaButtonUrl?: string;
  containerWidth: '1024px' | '1200px' | '1280px' | '1440px' | '100%' | string;
  height: string;
  description: string;
}

export const PUBLIC_TOPBAR_TEMPLATES: PublicTopbarTemplate[] = [
  {
    key: 'topbar-minimal-centered',
    name: 'Minimal Centered Emblem',
    category: 'Minimal',
    layoutStyle: 'logo_center_split_nav',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: false,
    ctaButtonText: 'Book VIP Viewing',
    ctaButtonUrl: '/#contact',
    containerWidth: '1280px',
    height: '72px',
    description: 'Symmetric navigation split evenly around a centered architectural monogram.',
  },
  {
    key: 'topbar-luxury-transparent',
    name: 'Luxury Transparent Glass',
    category: 'Luxury',
    layoutStyle: 'logo_left_nav_right',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: false,
    ctaButtonText: 'Private Concierge',
    ctaButtonUrl: '/portal',
    containerWidth: '1440px',
    height: '80px',
    description: 'Ultra-thin 1px gold border floating effortlessly over hero video and 3D scenes.',
  },
  {
    key: 'topbar-split-navigation',
    name: 'Atelier Split Navigation',
    category: 'Editorial',
    layoutStyle: 'logo_center_split_nav',
    sticky: false,
    backdropBlur: false,
    searchSlotEnabled: true,
    ctaButtonText: 'Client Portal',
    ctaButtonUrl: '/portal',
    containerWidth: '1280px',
    height: '88px',
    description: 'Classic high-fashion split navigation with integrated luxury search drawer trigger.',
  },
  {
    key: 'topbar-floating-pill',
    name: 'Floating Pill Capsule',
    category: 'Modern',
    layoutStyle: 'floating_pill',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: false,
    ctaButtonText: 'Explore',
    ctaButtonUrl: '/properties',
    containerWidth: '1024px',
    height: '60px',
    description: 'Detached capsule suspended at the top viewport with gentle drop shadow.',
  },
  {
    key: 'topbar-full-width-editorial',
    name: 'Broadsheet Full-Width Editorial',
    category: 'Editorial',
    layoutStyle: 'logo_left_nav_right',
    sticky: true,
    backdropBlur: false,
    searchSlotEnabled: true,
    ctaButtonText: 'View Residences',
    ctaButtonUrl: '/properties',
    containerWidth: '100%',
    height: '76px',
    description: 'Spanning edge-to-edge with crisp hairline divider and architectural typography.',
  },
  {
    key: 'topbar-mega-menu-luxury',
    name: 'Grand Mega Menu Header',
    category: 'Luxury',
    layoutStyle: 'mega_menu',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: true,
    ctaButtonText: 'VIP Invitation',
    ctaButtonUrl: '/login',
    containerWidth: '1440px',
    height: '84px',
    description: 'Expanded hover dropdowns showing 3D model thumbnails and active unit availability.',
  },
  {
    key: 'topbar-property-search-nav',
    name: 'Integrated Property Search Bar',
    category: 'Functional',
    layoutStyle: 'search_first',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: true,
    ctaButtonText: 'Search Units',
    ctaButtonUrl: '/properties',
    containerWidth: '1440px',
    height: '80px',
    description: 'Embedded property search pill directly inside header for high-volume brokerage portals.',
  },
  {
    key: 'topbar-compact-double-row',
    name: 'Double-Deck Executive Utility',
    category: 'Corporate',
    layoutStyle: 'double_row',
    sticky: true,
    backdropBlur: false,
    searchSlotEnabled: true,
    ctaButtonText: 'Schedule Consultation',
    ctaButtonUrl: '/#contact',
    containerWidth: '1280px',
    height: '104px',
    description: 'Top utility strip (phone, WhatsApp, currency) above primary navigation row.',
  },
  {
    key: 'topbar-dark-glass',
    name: 'Obsidian Frosted Glass',
    category: 'Modern',
    layoutStyle: 'logo_left_nav_right',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: false,
    ctaButtonText: 'Sign In',
    ctaButtonUrl: '/login',
    containerWidth: '1280px',
    height: '72px',
    description: 'Deep black glassmorphism with high-contrast glowing active states.',
  },
  {
    key: 'topbar-light-architectural',
    name: 'Nordic Monolith Header',
    category: 'Architectural',
    layoutStyle: 'logo_left_nav_right',
    sticky: true,
    backdropBlur: false,
    searchSlotEnabled: false,
    ctaButtonText: 'Floorplans',
    ctaButtonUrl: '/properties',
    containerWidth: '1440px',
    height: '68px',
    description: '0px border radius, technical uppercase links, and stark monolithic styling.',
  },
  {
    key: 'topbar-overlay-hero',
    name: 'Hero Canvas Floating Overlay',
    category: 'Luxury',
    layoutStyle: 'overlay_hero',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: false,
    ctaButtonText: 'Discover',
    ctaButtonUrl: '/#virtual-tour',
    containerWidth: '1280px',
    height: '80px',
    description: 'Starts 100% transparent over 3D canvas and solidifies dynamically on downward scroll.',
  },
  {
    key: 'topbar-sidebar-launch-nav',
    name: 'Curtain Drawer Trigger Header',
    category: 'Minimal',
    layoutStyle: 'sidebar_trigger',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: false,
    ctaButtonText: 'Menu',
    ctaButtonUrl: '#menu',
    containerWidth: '100%',
    height: '70px',
    description: 'Distraction-free brand logo with prominent burger trigger launching full-screen menu.',
  },
  {
    key: 'topbar-high-contrast-bar',
    name: 'High-Contrast Technical Bar',
    category: 'Functional',
    layoutStyle: 'logo_left_nav_right',
    sticky: true,
    backdropBlur: false,
    searchSlotEnabled: true,
    ctaButtonText: 'Catalog',
    ctaButtonUrl: '/properties',
    containerWidth: '1440px',
    height: '64px',
    description: 'Solid dark container with bright lime accent highlights and accessible keyboard outlines.',
  },
  {
    key: 'topbar-classic-estate',
    name: 'Heritage Estate Manor',
    category: 'Editorial',
    layoutStyle: 'double_row',
    sticky: false,
    backdropBlur: false,
    searchSlotEnabled: false,
    ctaButtonText: 'Direct Advisory',
    ctaButtonUrl: 'tel:+92518809911',
    containerWidth: '1200px',
    height: '96px',
    description: 'Traditional luxury serif header with direct concierge telephone inquiry banner.',
  },
  {
    key: 'topbar-saas-minimal',
    name: 'Clean SaaS PropTech Nav',
    category: 'Corporate',
    layoutStyle: 'logo_left_nav_right',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: true,
    ctaButtonText: 'Get Started',
    ctaButtonUrl: '/login',
    containerWidth: '1280px',
    height: '68px',
    description: 'Standard Silicon Valley layout: Logo left, center nav links, primary CTA right.',
  },
  {
    key: 'topbar-monochrome-stark',
    name: 'Monochrome Stark Bar',
    category: 'Minimal',
    layoutStyle: 'logo_left_nav_right',
    sticky: true,
    backdropBlur: false,
    searchSlotEnabled: false,
    ctaButtonText: 'Index',
    ctaButtonUrl: '/properties',
    containerWidth: '1360px',
    height: '60px',
    description: 'Strict black and white architectural navigation bar without decorative frills.',
  },
  {
    key: 'topbar-warm-terracotta',
    name: 'Mediterranean Terracotta Header',
    category: 'Luxury',
    layoutStyle: 'logo_center_split_nav',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: false,
    ctaButtonText: 'Visit Villas',
    ctaButtonUrl: '/properties?type=Villa',
    containerWidth: '1280px',
    height: '76px',
    description: 'Warm linen backdrop with terracotta accents and Playfair Display branding.',
  },
  {
    key: 'topbar-cyber-neon',
    name: 'Cyberpunk Skyline Navigation',
    category: 'Modern',
    layoutStyle: 'logo_left_nav_right',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: true,
    ctaButtonText: 'Live Stream',
    ctaButtonUrl: '/#virtual-tour',
    containerWidth: '1440px',
    height: '70px',
    description: 'Dark midnight blue with glowing magenta underglow line and monospace badges.',
  },
  {
    key: 'topbar-art-deco-brass',
    name: 'Roaring Deco Brass Header',
    category: 'Editorial',
    layoutStyle: 'logo_center_split_nav',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: false,
    ctaButtonText: 'Enter Private Sale',
    ctaButtonUrl: '/login',
    containerWidth: '1200px',
    height: '84px',
    description: 'Deep emerald background with polished brass geometric borders and Cinzel serif.',
  },
  {
    key: 'topbar-resort-travertine',
    name: 'Travertine Resort Header',
    category: 'Luxury',
    layoutStyle: 'logo_left_nav_right',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: false,
    ctaButtonText: 'Reserve Penthouse',
    ctaButtonUrl: '/#contact',
    containerWidth: '1280px',
    height: '78px',
    description: 'Warm limestone texture with espresso typography and relaxed luxury pacing.',
  },
  {
    key: 'topbar-compact-glass-dock',
    name: 'Docked Glass Island',
    category: 'Modern',
    layoutStyle: 'floating_pill',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: false,
    ctaButtonText: 'Log In',
    ctaButtonUrl: '/login',
    containerWidth: '1100px',
    height: '64px',
    description: 'Floating glass island centered horizontally with rounded-full border treatment.',
  },
  {
    key: 'topbar-metropolitan-loft',
    name: 'Urban Loft Wireframe Header',
    category: 'Architectural',
    layoutStyle: 'logo_left_nav_right',
    sticky: true,
    backdropBlur: false,
    searchSlotEnabled: true,
    ctaButtonText: 'Schedule Tour',
    ctaButtonUrl: '/#contact',
    containerWidth: '1440px',
    height: '72px',
    description: 'Graphite slate bar with amber accents and technical coordinate display.',
  },
  {
    key: 'topbar-wabi-sabi-wood',
    name: 'Kyoto Wabi-Sabi Strip',
    category: 'Minimal',
    layoutStyle: 'logo_center_split_nav',
    sticky: false,
    backdropBlur: false,
    searchSlotEnabled: false,
    ctaButtonText: 'Sanctuary',
    ctaButtonUrl: '/properties',
    containerWidth: '1180px',
    height: '80px',
    description: 'Understated charcoal layout celebrating negative space and tranquil restraint.',
  },
  {
    key: 'topbar-scandinavian-light',
    name: 'Nordic Clean Light Bar',
    category: 'Minimal',
    layoutStyle: 'logo_left_nav_right',
    sticky: true,
    backdropBlur: true,
    searchSlotEnabled: true,
    ctaButtonText: 'Inquire',
    ctaButtonUrl: '/#contact',
    containerWidth: '1280px',
    height: '70px',
    description: 'Soft birch tones and airy typography with pill-shaped search input.',
  },
  {
    key: 'topbar-high-rise-commercial',
    name: 'Skyline Commercial Portal Nav',
    category: 'Corporate',
    layoutStyle: 'double_row',
    sticky: true,
    backdropBlur: false,
    searchSlotEnabled: true,
    ctaButtonText: 'Leasing Portal',
    ctaButtonUrl: '/portal',
    containerWidth: '1440px',
    height: '92px',
    description: 'Designed for multi-tenant commercial office towers with tenant portal action.',
  },
];

export function getTopbarTemplateByKey(key: string): PublicTopbarTemplate {
  return PUBLIC_TOPBAR_TEMPLATES.find((t) => t.key === key) || PUBLIC_TOPBAR_TEMPLATES[0];
}
