export interface SkeletonTemplate {
  key: string;
  name: string;
  category: 'Public' | 'Dashboard' | 'Card' | 'Form' | '3D' | 'Data' | string;
  contentType:
    | 'public_homepage'
    | 'topbar'
    | 'footer'
    | 'property_card'
    | 'property_detail'
    | 'dashboard_shell'
    | 'data_table'
    | 'form_stacked'
    | 'viewer_3d'
    | 'user_profile'
    | 'analytics_grid'
    | 'invoice_ledger';
  animation: 'pulse' | 'shimmer' | 'wave' | 'static';
  speedMs: number;
  baseColor: string;
  highlightColor: string;
  radius: string;
  description: string;
}

export const SKELETON_TEMPLATES: SkeletonTemplate[] = [
  {
    key: 'skel-property-card',
    name: 'Property Listing Card Skeleton',
    category: 'Card',
    contentType: 'property_card',
    animation: 'shimmer',
    speedMs: 1500,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: 'var(--radius, 0.5rem)',
    description: 'Accurately matches aspect ratio of property image, title line, specs pill row, and price tag.',
  },
  {
    key: 'skel-property-detail',
    name: 'Property Detail Page Showcase Skeleton',
    category: 'Public',
    contentType: 'property_detail',
    animation: 'shimmer',
    speedMs: 1800,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: 'var(--radius-lg, 0.75rem)',
    description: 'Header hero block, photo gallery carousel placeholders, and specs grid.',
  },
  {
    key: 'skel-viewer-3d',
    name: 'PlayCanvas 3D Spatial Canvas Skeleton',
    category: '3D',
    contentType: 'viewer_3d',
    animation: 'pulse',
    speedMs: 2000,
    baseColor: 'var(--surface-1, #111726)',
    highlightColor: 'rgba(212, 175, 55, 0.15)',
    radius: 'var(--radius-lg, 0.75rem)',
    description: 'Displays 3D wireframe bounding cube placeholder with floating camera control pills.',
  },
  {
    key: 'skel-data-table',
    name: 'Executive CRM Data Table Skeleton',
    category: 'Data',
    contentType: 'data_table',
    animation: 'shimmer',
    speedMs: 1400,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: '0.25rem',
    description: 'Header column row plus 5 alternating simulated data record rows.',
  },
  {
    key: 'skel-dashboard-shell',
    name: 'Complete Dashboard Shell Skeleton',
    category: 'Dashboard',
    contentType: 'dashboard_shell',
    animation: 'pulse',
    speedMs: 1600,
    baseColor: 'var(--surface-1, #111726)',
    highlightColor: 'var(--surface-2, #1e293b)',
    radius: 'var(--radius, 0.5rem)',
    description: 'Sidebar rail, top utility bar, and primary viewport grid placeholders.',
  },
  {
    key: 'skel-form-stacked',
    name: 'Standard Stacked Form Skeleton',
    category: 'Form',
    contentType: 'form_stacked',
    animation: 'shimmer',
    speedMs: 1500,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: 'var(--radius, 0.5rem)',
    description: 'Simulates label bars, rectangular input fields, and submit button.',
  },
  {
    key: 'skel-public-topbar',
    name: 'Public Header Bar Skeleton',
    category: 'Public',
    contentType: 'topbar',
    animation: 'shimmer',
    speedMs: 1200,
    baseColor: 'var(--surface-1, #111726)',
    highlightColor: 'var(--surface-2, #1e293b)',
    radius: 'var(--radius, 0.5rem)',
    description: 'Brand emblem on left, 4 nav pills in center, and action CTA button right.',
  },
  {
    key: 'skel-public-footer',
    name: 'Multi-Column Footer Skeleton',
    category: 'Public',
    contentType: 'footer',
    animation: 'pulse',
    speedMs: 2000,
    baseColor: 'var(--surface-1, #111726)',
    highlightColor: 'var(--surface-2, #1e293b)',
    radius: '0.25rem',
    description: 'Four multi-column link stacks with copyright bar across bottom.',
  },
  {
    key: 'skel-analytics-grid',
    name: 'Analytics KPI Metrics Grid Skeleton',
    category: 'Data',
    contentType: 'analytics_grid',
    animation: 'shimmer',
    speedMs: 1400,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: 'var(--radius, 0.5rem)',
    description: 'Four KPI statistic cards with sparkline graph silhouettes.',
  },
  {
    key: 'skel-user-profile',
    name: 'User Identity & Avatar Card Skeleton',
    category: 'Dashboard',
    contentType: 'user_profile',
    animation: 'shimmer',
    speedMs: 1500,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: '9999px',
    description: 'Circular avatar silhouette with user name and role badge placeholder.',
  },
  {
    key: 'skel-invoice-ledger',
    name: 'Invoice Financial Ledger Skeleton',
    category: 'Data',
    contentType: 'invoice_ledger',
    animation: 'shimmer',
    speedMs: 1600,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: '0.375rem',
    description: 'Invoice number, recipient, amount, balance, and status chip placeholders.',
  },
  {
    key: 'skel-public-homepage',
    name: 'Public Homepage Hero & Grid Skeleton',
    category: 'Public',
    contentType: 'public_homepage',
    animation: 'shimmer',
    speedMs: 1800,
    baseColor: 'var(--surface-1, #111726)',
    highlightColor: 'var(--surface-2, #1e293b)',
    radius: 'var(--radius, 0.5rem)',
    description: 'Full-bleed hero banner placeholder followed by 3-column listing grid.',
  },
  {
    key: 'skel-wave-luxury-card',
    name: 'Gentle Wave Luxury Villa Card',
    category: 'Card',
    contentType: 'property_card',
    animation: 'wave',
    speedMs: 2200,
    baseColor: 'rgba(212, 175, 55, 0.08)',
    highlightColor: 'rgba(212, 175, 55, 0.2)',
    radius: 'var(--radius-lg, 0.75rem)',
    description: 'Warm gold undulating gradient wave for luxury villa listing cards.',
  },
  {
    key: 'skel-static-accessible',
    name: 'Static Reduced-Motion Skeleton',
    category: 'Public',
    contentType: 'property_card',
    animation: 'static',
    speedMs: 0,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-2, #1e293b)',
    radius: 'var(--radius, 0.5rem)',
    description: 'Motion-free solid placeholder honoring prefers-reduced-motion system preferences.',
  },
  {
    key: 'skel-deal-pipeline',
    name: 'Deals Kanban Stage Column Skeleton',
    category: 'Data',
    contentType: 'data_table',
    animation: 'pulse',
    speedMs: 1600,
    baseColor: 'var(--surface-1, #111726)',
    highlightColor: 'var(--surface-2, #1e293b)',
    radius: 'var(--radius, 0.5rem)',
    description: 'Four vertical deal stage columns containing simulated deal cards.',
  },
  {
    key: 'skel-appointment-calendar',
    name: 'Viewing Appointments Calendar Skeleton',
    category: 'Data',
    contentType: 'data_table',
    animation: 'shimmer',
    speedMs: 1500,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: '0.25rem',
    description: '7-column weekly time slot calendar grid with appointment blocks.',
  },
  {
    key: 'skel-customer-portal-feed',
    name: 'Customer Portal Timeline Feed Skeleton',
    category: 'Dashboard',
    contentType: 'dashboard_shell',
    animation: 'shimmer',
    speedMs: 1700,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: 'var(--radius, 0.5rem)',
    description: 'Vertical milestone progression nodes and active deal summary card.',
  },
  {
    key: 'skel-compact-sidebar-rail',
    name: 'Sidebar Icon Rail Skeleton',
    category: 'Dashboard',
    contentType: 'dashboard_shell',
    animation: 'pulse',
    speedMs: 1500,
    baseColor: 'var(--surface-1, #111726)',
    highlightColor: 'var(--surface-2, #1e293b)',
    radius: '9999px',
    description: 'Vertical stack of 6 circular icon placeholders.',
  },
  {
    key: 'skel-media-gallery-grid',
    name: 'Media Assets Gallery Grid Skeleton',
    category: 'Public',
    contentType: 'property_detail',
    animation: 'shimmer',
    speedMs: 1600,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: 'var(--radius, 0.5rem)',
    description: 'Masonry photo gallery grid placeholder with varying aspect ratios.',
  },
  {
    key: 'skel-search-dropdown-results',
    name: 'Global Search Dropdown Results Skeleton',
    category: 'Public',
    contentType: 'topbar',
    animation: 'shimmer',
    speedMs: 1200,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: 'var(--radius, 0.5rem)',
    description: 'Quick result suggestions showing icon, title, category, and price line.',
  },
  {
    key: 'skel-lead-conversion-modal',
    name: 'Lead Conversion Dialog Skeleton',
    category: 'Form',
    contentType: 'form_stacked',
    animation: 'pulse',
    speedMs: 1400,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: 'var(--radius-lg, 0.75rem)',
    description: 'Customer password generation field, email checkbox, and submit buttons.',
  },
  {
    key: 'skel-audit-log-stream',
    name: 'Realtime Audit Log Stream Skeleton',
    category: 'Data',
    contentType: 'data_table',
    animation: 'shimmer',
    speedMs: 1300,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: '0.25rem',
    description: 'Security badge, timestamp, user email, action identifier, and payload diff.',
  },
  {
    key: 'skel-otp-verification-boxes',
    name: 'Six-Box OTP Input Skeleton',
    category: 'Form',
    contentType: 'form_stacked',
    animation: 'pulse',
    speedMs: 1500,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: '0.5rem',
    description: 'Six distinct rounded square input placeholders with resend countdown line.',
  },
  {
    key: 'skel-unit-inventory-matrix',
    name: '3D Floor Unit Inventory Matrix Skeleton',
    category: '3D',
    contentType: 'viewer_3d',
    animation: 'shimmer',
    speedMs: 1700,
    baseColor: 'var(--surface-2, #1e293b)',
    highlightColor: 'var(--surface-3, #334155)',
    radius: '0.375rem',
    description: 'Floor selector tabs on top and unit inventory cards below with price and status.',
  },
  {
    key: 'skel-mobile-dock-bottom',
    name: 'Mobile Bottom Dock Skeleton',
    category: 'Public',
    contentType: 'topbar',
    animation: 'pulse',
    speedMs: 1500,
    baseColor: 'var(--surface-1, #111726)',
    highlightColor: 'var(--surface-2, #1e293b)',
    radius: '9999px',
    description: 'Bottom floating pill dock with 4 icon placeholders for mobile screens.',
  },
];

export function getSkeletonTemplateByKey(key: string): SkeletonTemplate {
  return SKELETON_TEMPLATES.find((s) => s.key === key) || SKELETON_TEMPLATES[0];
}
