import { ThemeDefinition, DEFAULT_DESIGN_TOKENS } from './tokens';

export const SYSTEM_THEMES: ThemeDefinition[] = [
  {
    key: 'luxury-dark',
    name: 'Aura Luxury Dark',
    category: 'Luxury',
    description: 'Deep obsidian surfaces with polished gold accents and refined serif typography.',
    mode: 'dual',
    tokens: {
      colors: {
        background: '#0a0d14',
        foreground: '#f8fafc',
        surface1: '#111726',
        surface2: '#182033',
        surface3: '#222d47',
        card: '#111726',
        cardForeground: '#f8fafc',
        primary: '#d4af37',
        primaryForeground: '#0a0d14',
        secondary: '#94a3b8',
        secondaryForeground: '#ffffff',
        accent: '#f59e0b',
        accentForeground: '#0a0d14',
        muted: '#1e293b',
        mutedForeground: '#94a3b8',
        border: 'rgba(212, 175, 55, 0.2)',
        focus: '#d4af37',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.25rem',
        radiusMd: '0.5rem',
        radiusLg: '0.75rem',
        radiusFull: '9999px',
        shadowPreset: 'dramatic',
        shadowValue: '0 20px 40px -15px rgba(0, 0, 0, 0.7)',
        containerMaxWidth: '1280px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Cormorant Garamond, serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Inter, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.02em',
        lineHeight: '1.6',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
    componentDefaults: {
      buttonRadius: '0.25rem',
      cardBorder: '1px solid rgba(212, 175, 55, 0.2)',
      navbarStyle: 'glass',
    },
  },
  {
    key: 'luxury-light',
    name: 'Alabaster Palace',
    category: 'Luxury',
    description: 'Ivory alabaster tones with warm champagne borders and elegant editorial serifs.',
    mode: 'light',
    tokens: {
      colors: {
        background: '#fcfbf9',
        foreground: '#1c1917',
        surface1: '#ffffff',
        surface2: '#f5f2eb',
        surface3: '#ece6da',
        card: '#ffffff',
        cardForeground: '#1c1917',
        primary: '#b45309',
        primaryForeground: '#ffffff',
        secondary: '#78716c',
        secondaryForeground: '#ffffff',
        accent: '#d97706',
        accentForeground: '#ffffff',
        muted: '#f5f2eb',
        mutedForeground: '#78716c',
        border: '#e8e2d9',
        focus: '#b45309',
        success: '#059669',
        warning: '#d97706',
        danger: '#dc2626',
      },
      metrics: {
        radiusSm: '0.25rem',
        radiusMd: '0.5rem',
        radiusLg: '0.75rem',
        radiusFull: '9999px',
        shadowPreset: 'soft',
        shadowValue: '0 10px 30px -10px rgba(180, 83, 9, 0.08)',
        containerMaxWidth: '1280px',
        spacingScale: '1.05rem',
      },
      typography: {
        headingFont: 'Playfair Display, serif',
        bodyFont: 'Plus Jakarta Sans, sans-serif',
        uiFont: 'Plus Jakarta Sans, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '-0.01em',
        lineHeight: '1.6',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'architectural',
    name: 'Brutal Slate & Glass',
    category: 'Architectural',
    description: 'Monolithic concrete slate with precise cyan technical accents and sharp geometry.',
    mode: 'dark',
    tokens: {
      colors: {
        background: '#0e1117',
        foreground: '#f1f5f9',
        surface1: '#161b24',
        surface2: '#1f2633',
        surface3: '#293242',
        card: '#161b24',
        cardForeground: '#f1f5f9',
        primary: '#06b6d4',
        primaryForeground: '#0e1117',
        secondary: '#64748b',
        secondaryForeground: '#ffffff',
        accent: '#38bdf8',
        accentForeground: '#0e1117',
        muted: '#1e2532',
        mutedForeground: '#94a3b8',
        border: '#334155',
        focus: '#06b6d4',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0px',
        radiusMd: '0px',
        radiusLg: '0px',
        radiusFull: '0px',
        shadowPreset: 'none',
        shadowValue: 'none',
        containerMaxWidth: '1440px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Space Grotesk, sans-serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Space Grotesk, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '-0.03em',
        lineHeight: '1.45',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'editorial-serif',
    name: 'Vogue Heritage Residence',
    category: 'Editorial',
    description: 'High-fashion editorial layout inspired by architectural design chronicles.',
    mode: 'dual',
    tokens: {
      colors: {
        background: '#fdfbf7',
        foreground: '#111827',
        surface1: '#ffffff',
        surface2: '#f3eee3',
        surface3: '#e5decb',
        card: '#ffffff',
        cardForeground: '#111827',
        primary: '#111827',
        primaryForeground: '#ffffff',
        secondary: '#4b5563',
        secondaryForeground: '#ffffff',
        accent: '#854d0e',
        accentForeground: '#ffffff',
        muted: '#f3eee3',
        mutedForeground: '#6b7280',
        border: '#d6cdb7',
        focus: '#111827',
        success: '#15803d',
        warning: '#b45309',
        danger: '#b91c1c',
      },
      metrics: {
        radiusSm: '0.125rem',
        radiusMd: '0.25rem',
        radiusLg: '0.375rem',
        radiusFull: '9999px',
        shadowPreset: 'soft',
        shadowValue: '0 4px 20px -2px rgba(0, 0, 0, 0.05)',
        containerMaxWidth: '1200px',
        spacingScale: '1.125rem',
      },
      typography: {
        headingFont: 'Newsreader, serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Inter, sans-serif',
        headingWeight: '500',
        bodyWeight: '400',
        letterSpacing: '0.01em',
        lineHeight: '1.7',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'modern-corporate',
    name: 'Aura Premier Corporate',
    category: 'Corporate',
    description: 'Executive navy blue and crisp white cards tailored for institutional investment brokerages.',
    mode: 'dual',
    tokens: {
      colors: {
        background: '#0b132b',
        foreground: '#f8fafc',
        surface1: '#1c2541',
        surface2: '#253259',
        surface3: '#3a506b',
        card: '#1c2541',
        cardForeground: '#f8fafc',
        primary: '#3b82f6',
        primaryForeground: '#ffffff',
        secondary: '#60a5fa',
        secondaryForeground: '#0b132b',
        accent: '#38bdf8',
        accentForeground: '#0b132b',
        muted: '#1f2a47',
        mutedForeground: '#94a3b8',
        border: 'rgba(59, 130, 246, 0.2)',
        focus: '#3b82f6',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.375rem',
        radiusMd: '0.5rem',
        radiusLg: '0.75rem',
        radiusFull: '9999px',
        shadowPreset: 'medium',
        shadowValue: '0 12px 28px -6px rgba(11, 19, 43, 0.6)',
        containerMaxWidth: '1360px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Inter, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '-0.02em',
        lineHeight: '1.5',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'minimal-glass',
    name: 'Cosmic Glassmorphic',
    category: 'Minimal',
    description: 'Translucent frosted obsidian with neon violet backlights and luminous edge outlines.',
    mode: 'dark',
    tokens: {
      colors: {
        background: '#07080d',
        foreground: '#f5f3ff',
        surface1: 'rgba(19, 21, 36, 0.65)',
        surface2: 'rgba(30, 34, 58, 0.75)',
        surface3: 'rgba(45, 50, 85, 0.85)',
        card: 'rgba(19, 21, 36, 0.65)',
        cardForeground: '#f5f3ff',
        primary: '#8b5cf6',
        primaryForeground: '#ffffff',
        secondary: '#a78bfa',
        secondaryForeground: '#07080d',
        accent: '#ec4899',
        accentForeground: '#ffffff',
        muted: 'rgba(255, 255, 255, 0.05)',
        mutedForeground: '#a1a1aa',
        border: 'rgba(139, 92, 246, 0.25)',
        focus: '#a78bfa',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.5rem',
        radiusMd: '0.75rem',
        radiusLg: '1.25rem',
        radiusFull: '9999px',
        shadowPreset: 'floating',
        shadowValue: '0 20px 50px rgba(139, 92, 246, 0.15)',
        containerMaxWidth: '1280px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Outfit, sans-serif',
        bodyFont: 'DM Sans, sans-serif',
        uiFont: 'Outfit, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '-0.01em',
        lineHeight: '1.55',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'warm-neutral',
    name: 'Nordic Cashmere',
    category: 'Warm',
    description: 'Calm cashmere and linen hues radiating natural comfort and organic luxury.',
    mode: 'light',
    tokens: {
      colors: {
        background: '#f6f4ee',
        foreground: '#292524',
        surface1: '#ffffff',
        surface2: '#eae5d9',
        surface3: '#dcd5c4',
        card: '#ffffff',
        cardForeground: '#292524',
        primary: '#78350f',
        primaryForeground: '#ffffff',
        secondary: '#57534e',
        secondaryForeground: '#ffffff',
        accent: '#d97706',
        accentForeground: '#ffffff',
        muted: '#eae5d9',
        mutedForeground: '#78716c',
        border: '#d6cfbf',
        focus: '#78350f',
        success: '#16a34a',
        warning: '#ea580c',
        danger: '#dc2626',
      },
      metrics: {
        radiusSm: '0.5rem',
        radiusMd: '0.875rem',
        radiusLg: '1.25rem',
        radiusFull: '9999px',
        shadowPreset: 'soft',
        shadowValue: '0 8px 24px -4px rgba(41, 37, 36, 0.06)',
        containerMaxWidth: '1240px',
        spacingScale: '1.1rem',
      },
      typography: {
        headingFont: 'Outfit, sans-serif',
        bodyFont: 'DM Sans, sans-serif',
        uiFont: 'DM Sans, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '-0.01em',
        lineHeight: '1.6',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'premium-black',
    name: 'OLED Pure Shadow',
    category: 'Modern',
    description: 'Pitch-black contrast canvas with platinum highlights and razor-sharp typecraft.',
    mode: 'dark',
    tokens: {
      colors: {
        background: '#000000',
        foreground: '#ffffff',
        surface1: '#0a0a0a',
        surface2: '#141414',
        surface3: '#1f1f1f',
        card: '#0a0a0a',
        cardForeground: '#ffffff',
        primary: '#ffffff',
        primaryForeground: '#000000',
        secondary: '#a1a1aa',
        secondaryForeground: '#000000',
        accent: '#e2e8f0',
        accentForeground: '#000000',
        muted: '#18181b',
        mutedForeground: '#71717a',
        border: '#27272a',
        focus: '#ffffff',
        success: '#22c55e',
        warning: '#eab308',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.125rem',
        radiusMd: '0.25rem',
        radiusLg: '0.375rem',
        radiusFull: '9999px',
        shadowPreset: 'none',
        shadowValue: 'none',
        containerMaxWidth: '1360px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Syne, sans-serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Inter, sans-serif',
        headingWeight: '800',
        bodyWeight: '400',
        letterSpacing: '-0.04em',
        lineHeight: '1.4',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'brutalist',
    name: 'Neo Brutalist Estate',
    category: 'Architectural',
    description: 'Thick black architectural borders, bold primary colors, and zero border radius.',
    mode: 'light',
    tokens: {
      colors: {
        background: '#fffdfa',
        foreground: '#000000',
        surface1: '#ffffff',
        surface2: '#fef08a',
        surface3: '#bbf7d0',
        card: '#ffffff',
        cardForeground: '#000000',
        primary: '#000000',
        primaryForeground: '#ffffff',
        secondary: '#2563eb',
        secondaryForeground: '#ffffff',
        accent: '#f97316',
        accentForeground: '#000000',
        muted: '#f4f4f5',
        mutedForeground: '#52525b',
        border: '#000000',
        focus: '#2563eb',
        success: '#16a34a',
        warning: '#f59e0b',
        danger: '#dc2626',
      },
      metrics: {
        radiusSm: '0px',
        radiusMd: '0px',
        radiusLg: '0px',
        radiusFull: '0px',
        shadowPreset: 'dramatic',
        shadowValue: '5px 5px 0px #000000',
        containerMaxWidth: '1320px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Archivo Black, sans-serif',
        bodyFont: 'Space Grotesk, sans-serif',
        uiFont: 'Space Grotesk, sans-serif',
        headingWeight: '900',
        bodyWeight: '500',
        letterSpacing: '-0.03em',
        lineHeight: '1.35',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'soft-glass',
    name: 'Frosted Crystal Oasis',
    category: 'Minimal',
    description: 'Luminescent semi-transparent pearl panels with refreshing mint accents.',
    mode: 'dual',
    tokens: {
      colors: {
        background: '#0d131f',
        foreground: '#f0fdf4',
        surface1: 'rgba(255, 255, 255, 0.06)',
        surface2: 'rgba(255, 255, 255, 0.1)',
        surface3: 'rgba(255, 255, 255, 0.16)',
        card: 'rgba(255, 255, 255, 0.07)',
        cardForeground: '#f0fdf4',
        primary: '#14b8a6',
        primaryForeground: '#0d131f',
        secondary: '#2dd4bf',
        secondaryForeground: '#0d131f',
        accent: '#38bdf8',
        accentForeground: '#0d131f',
        muted: 'rgba(255, 255, 255, 0.05)',
        mutedForeground: '#94a3b8',
        border: 'rgba(20, 184, 166, 0.25)',
        focus: '#2dd4bf',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.625rem',
        radiusMd: '1rem',
        radiusLg: '1.5rem',
        radiusFull: '9999px',
        shadowPreset: 'floating',
        shadowValue: '0 20px 40px -10px rgba(20, 184, 166, 0.15)',
        containerMaxWidth: '1280px',
        spacingScale: '1.05rem',
      },
      typography: {
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Plus Jakarta Sans, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '-0.02em',
        lineHeight: '1.55',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'high-contrast',
    name: 'Cyber Lime High Contrast',
    category: 'High-Tech',
    description: 'AAA accessibility optimized contrast with ultra-vivid lime highlights on dark charcoal.',
    mode: 'dark',
    tokens: {
      colors: {
        background: '#050505',
        foreground: '#ffffff',
        surface1: '#121212',
        surface2: '#1e1e1e',
        surface3: '#2a2a2a',
        card: '#121212',
        cardForeground: '#ffffff',
        primary: '#a3e635',
        primaryForeground: '#050505',
        secondary: '#facc15',
        secondaryForeground: '#050505',
        accent: '#38bdf8',
        accentForeground: '#050505',
        muted: '#262626',
        mutedForeground: '#a3a3a3',
        border: '#404040',
        focus: '#a3e635',
        success: '#4ade80',
        warning: '#facc15',
        danger: '#f87171',
      },
      metrics: {
        radiusSm: '0.25rem',
        radiusMd: '0.375rem',
        radiusLg: '0.5rem',
        radiusFull: '9999px',
        shadowPreset: 'medium',
        shadowValue: '0 0 0 1px #404040',
        containerMaxWidth: '1320px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Inter, sans-serif',
        headingWeight: '800',
        bodyWeight: '500',
        letterSpacing: '-0.02em',
        lineHeight: '1.5',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'mediterranean',
    name: 'Riviera Terracotta',
    category: 'Warm',
    description: 'Sun-kissed terracotta tiles paired with deep Aegean blue and whitewashed stone.',
    mode: 'light',
    tokens: {
      colors: {
        background: '#fffbf5',
        foreground: '#1c1917',
        surface1: '#ffffff',
        surface2: '#fbeee2',
        surface3: '#f3dcce',
        card: '#ffffff',
        cardForeground: '#1c1917',
        primary: '#c2410c',
        primaryForeground: '#ffffff',
        secondary: '#0369a1',
        secondaryForeground: '#ffffff',
        accent: '#ea580c',
        accentForeground: '#ffffff',
        muted: '#fbeee2',
        mutedForeground: '#78716c',
        border: '#fed7aa',
        focus: '#c2410c',
        success: '#15803d',
        warning: '#b45309',
        danger: '#b91c1c',
      },
      metrics: {
        radiusSm: '0.375rem',
        radiusMd: '0.75rem',
        radiusLg: '1.125rem',
        radiusFull: '9999px',
        shadowPreset: 'soft',
        shadowValue: '0 12px 30px -5px rgba(194, 65, 12, 0.08)',
        containerMaxWidth: '1260px',
        spacingScale: '1.05rem',
      },
      typography: {
        headingFont: 'Playfair Display, serif',
        bodyFont: 'DM Sans, sans-serif',
        uiFont: 'DM Sans, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.01em',
        lineHeight: '1.6',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'urban-slate',
    name: 'Metropolitan Loft',
    category: 'Modern',
    description: 'Industrial graphite concrete paired with warm loft amber illumination.',
    mode: 'dark',
    tokens: {
      colors: {
        background: '#181b20',
        foreground: '#e2e8f0',
        surface1: '#22272f',
        surface2: '#2c333e',
        surface3: '#38414e',
        card: '#22272f',
        cardForeground: '#e2e8f0',
        primary: '#f59e0b',
        primaryForeground: '#181b20',
        secondary: '#94a3b8',
        secondaryForeground: '#181b20',
        accent: '#fbbf24',
        accentForeground: '#181b20',
        muted: '#282f3a',
        mutedForeground: '#94a3b8',
        border: '#3e4856',
        focus: '#f59e0b',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.25rem',
        radiusMd: '0.375rem',
        radiusLg: '0.5rem',
        radiusFull: '9999px',
        shadowPreset: 'medium',
        shadowValue: '0 10px 25px rgba(0, 0, 0, 0.4)',
        containerMaxWidth: '1360px',
        spacingScale: '0.95rem',
      },
      typography: {
        headingFont: 'Space Grotesk, sans-serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Space Grotesk, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '-0.02em',
        lineHeight: '1.5',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'contemporary-gold',
    name: 'Majestic Gilded Estate',
    category: 'Luxury',
    description: 'Classic rich mahogany and 24-karat warm gold finishes for royal penthouses.',
    mode: 'dual',
    tokens: {
      colors: {
        background: '#120d09',
        foreground: '#fef3c7',
        surface1: '#1f160f',
        surface2: '#2d1f14',
        surface3: '#3e2c1c',
        card: '#1f160f',
        cardForeground: '#fef3c7',
        primary: '#f59e0b',
        primaryForeground: '#120d09',
        secondary: '#d97706',
        secondaryForeground: '#ffffff',
        accent: '#fbbf24',
        accentForeground: '#120d09',
        muted: '#2a1d13',
        mutedForeground: '#b45309',
        border: 'rgba(245, 158, 11, 0.3)',
        focus: '#fbbf24',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.25rem',
        radiusMd: '0.5rem',
        radiusLg: '0.75rem',
        radiusFull: '9999px',
        shadowPreset: 'dramatic',
        shadowValue: '0 25px 50px -12px rgba(245, 158, 11, 0.15)',
        containerMaxWidth: '1280px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Cinzel, serif',
        bodyFont: 'Montserrat, sans-serif',
        uiFont: 'Montserrat, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '0.04em',
        lineHeight: '1.6',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'high-fashion',
    name: 'Atelier Monochrome',
    category: 'Editorial',
    description: 'Minimalist high-fashion black & ivory contrast inspired by luxury architectural lookbooks.',
    mode: 'light',
    tokens: {
      colors: {
        background: '#faf9f6',
        foreground: '#09090b',
        surface1: '#ffffff',
        surface2: '#f4f2eb',
        surface3: '#e9e5d8',
        card: '#ffffff',
        cardForeground: '#09090b',
        primary: '#09090b',
        primaryForeground: '#ffffff',
        secondary: '#52525b',
        secondaryForeground: '#ffffff',
        accent: '#27272a',
        accentForeground: '#ffffff',
        muted: '#f4f2eb',
        mutedForeground: '#71717a',
        border: '#e4e0d2',
        focus: '#09090b',
        success: '#15803d',
        warning: '#b45309',
        danger: '#b91c1c',
      },
      metrics: {
        radiusSm: '0px',
        radiusMd: '0.125rem',
        radiusLg: '0.25rem',
        radiusFull: '9999px',
        shadowPreset: 'soft',
        shadowValue: '0 8px 30px rgba(0, 0, 0, 0.04)',
        containerMaxWidth: '1200px',
        spacingScale: '1.15rem',
      },
      typography: {
        headingFont: 'Bodoni Moda, serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Inter, sans-serif',
        headingWeight: '600',
        bodyWeight: '300',
        letterSpacing: '0.03em',
        lineHeight: '1.65',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'monochrome',
    name: 'Zinc Monolithic 50-Shades',
    category: 'Minimal',
    description: 'Pure neutral zinc grayscale palette free of color distraction for architectural purists.',
    mode: 'dark',
    tokens: {
      colors: {
        background: '#121214',
        foreground: '#f4f4f5',
        surface1: '#18181b',
        surface2: '#27272a',
        surface3: '#3f3f46',
        card: '#18181b',
        cardForeground: '#f4f4f5',
        primary: '#e4e4e7',
        primaryForeground: '#18181b',
        secondary: '#a1a1aa',
        secondaryForeground: '#18181b',
        accent: '#d4d4d8',
        accentForeground: '#18181b',
        muted: '#27272a',
        mutedForeground: '#71717a',
        border: '#3f3f46',
        focus: '#e4e4e7',
        success: '#22c55e',
        warning: '#eab308',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.375rem',
        radiusMd: '0.5rem',
        radiusLg: '0.75rem',
        radiusFull: '9999px',
        shadowPreset: 'medium',
        shadowValue: '0 10px 25px rgba(0, 0, 0, 0.5)',
        containerMaxWidth: '1300px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Inter, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '-0.02em',
        lineHeight: '1.5',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'nature-organic',
    name: 'Alpine Forest Retreat',
    category: 'Warm',
    description: 'Deep evergreen pine tones paired with earthy paper surfaces and botanical warmth.',
    mode: 'dual',
    tokens: {
      colors: {
        background: '#0a140f',
        foreground: '#f0fdf4',
        surface1: '#11221a',
        surface2: '#183025',
        surface3: '#204032',
        card: '#11221a',
        cardForeground: '#f0fdf4',
        primary: '#22c55e',
        primaryForeground: '#0a140f',
        secondary: '#86efac',
        secondaryForeground: '#0a140f',
        accent: '#a3e635',
        accentForeground: '#0a140f',
        muted: '#172b21',
        mutedForeground: '#86efac',
        border: 'rgba(34, 197, 94, 0.25)',
        focus: '#4ade80',
        success: '#22c55e',
        warning: '#facc15',
        danger: '#f87171',
      },
      metrics: {
        radiusSm: '0.5rem',
        radiusMd: '0.75rem',
        radiusLg: '1.25rem',
        radiusFull: '9999px',
        shadowPreset: 'medium',
        shadowValue: '0 15px 35px -5px rgba(10, 20, 15, 0.6)',
        containerMaxWidth: '1280px',
        spacingScale: '1.05rem',
      },
      typography: {
        headingFont: 'Outfit, sans-serif',
        bodyFont: 'Plus Jakarta Sans, sans-serif',
        uiFont: 'Plus Jakarta Sans, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '-0.01em',
        lineHeight: '1.55',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'warm-stone',
    name: 'Travertine Hospitality',
    category: 'Warm',
    description: 'Warm limestone beige with deep espresso contrast evoking 5-star resort residences.',
    mode: 'light',
    tokens: {
      colors: {
        background: '#f5f1ea',
        foreground: '#26221f',
        surface1: '#ffffff',
        surface2: '#e9e3d7',
        surface3: '#dbd3c2',
        card: '#ffffff',
        cardForeground: '#26221f',
        primary: '#5c4838',
        primaryForeground: '#ffffff',
        secondary: '#8a7460',
        secondaryForeground: '#ffffff',
        accent: '#c49a6c',
        accentForeground: '#ffffff',
        muted: '#e9e3d7',
        mutedForeground: '#7a6858',
        border: '#d6cbba',
        focus: '#5c4838',
        success: '#2e7d32',
        warning: '#c47d15',
        danger: '#c62828',
      },
      metrics: {
        radiusSm: '0.25rem',
        radiusMd: '0.5rem',
        radiusLg: '0.875rem',
        radiusFull: '9999px',
        shadowPreset: 'soft',
        shadowValue: '0 10px 25px -5px rgba(92, 72, 56, 0.08)',
        containerMaxWidth: '1240px',
        spacingScale: '1.1rem',
      },
      typography: {
        headingFont: 'Cormorant Garamond, serif',
        bodyFont: 'DM Sans, sans-serif',
        uiFont: 'DM Sans, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.02em',
        lineHeight: '1.6',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'slate-minimal',
    name: 'Nordic Slate & Frost',
    category: 'Minimal',
    description: 'Crisp light slate with cool undertones and ultra-clean whitespace balance.',
    mode: 'light',
    tokens: {
      colors: {
        background: '#f8fafc',
        foreground: '#0f172a',
        surface1: '#ffffff',
        surface2: '#f1f5f9',
        surface3: '#e2e8f0',
        card: '#ffffff',
        cardForeground: '#0f172a',
        primary: '#475569',
        primaryForeground: '#ffffff',
        secondary: '#64748b',
        secondaryForeground: '#ffffff',
        accent: '#0ea5e9',
        accentForeground: '#ffffff',
        muted: '#f1f5f9',
        mutedForeground: '#64748b',
        border: '#e2e8f0',
        focus: '#475569',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.375rem',
        radiusMd: '0.5rem',
        radiusLg: '0.75rem',
        radiusFull: '9999px',
        shadowPreset: 'soft',
        shadowValue: '0 4px 15px rgba(0, 0, 0, 0.04)',
        containerMaxWidth: '1280px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Inter, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '-0.02em',
        lineHeight: '1.5',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'scandinavian',
    name: 'Stockholm Light Wood',
    category: 'Warm',
    description: 'Bright airy Scandinavian spaces featuring pale birch accents and rounded geometry.',
    mode: 'light',
    tokens: {
      colors: {
        background: '#fbfbfa',
        foreground: '#18181b',
        surface1: '#ffffff',
        surface2: '#f4f4f2',
        surface3: '#eaeae6',
        card: '#ffffff',
        cardForeground: '#18181b',
        primary: '#27272a',
        primaryForeground: '#ffffff',
        secondary: '#71717a',
        secondaryForeground: '#ffffff',
        accent: '#e0a96d',
        accentForeground: '#18181b',
        muted: '#f4f4f2',
        mutedForeground: '#71717a',
        border: '#e4e4e0',
        focus: '#27272a',
        success: '#16a34a',
        warning: '#d97706',
        danger: '#dc2626',
      },
      metrics: {
        radiusSm: '0.5rem',
        radiusMd: '0.875rem',
        radiusLg: '1.25rem',
        radiusFull: '9999px',
        shadowPreset: 'soft',
        shadowValue: '0 6px 20px rgba(0, 0, 0, 0.03)',
        containerMaxWidth: '1260px',
        spacingScale: '1.05rem',
      },
      typography: {
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Plus Jakarta Sans, sans-serif',
        uiFont: 'Plus Jakarta Sans, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '-0.01em',
        lineHeight: '1.55',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'clean-saas',
    name: 'Silicon Valley PropTech',
    category: 'Corporate',
    description: 'Vibrant indigo brand identity with modern developer-grade UI elements.',
    mode: 'dual',
    tokens: {
      colors: {
        background: '#f8fafc',
        foreground: '#0f172a',
        surface1: '#ffffff',
        surface2: '#f1f5f9',
        surface3: '#e2e8f0',
        card: '#ffffff',
        cardForeground: '#0f172a',
        primary: '#4f46e5',
        primaryForeground: '#ffffff',
        secondary: '#6366f1',
        secondaryForeground: '#ffffff',
        accent: '#06b6d4',
        accentForeground: '#ffffff',
        muted: '#f1f5f9',
        mutedForeground: '#64748b',
        border: '#e2e8f0',
        focus: '#4f46e5',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.375rem',
        radiusMd: '0.5rem',
        radiusLg: '0.75rem',
        radiusFull: '9999px',
        shadowPreset: 'medium',
        shadowValue: '0 10px 25px -5px rgba(79, 70, 229, 0.1)',
        containerMaxWidth: '1320px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Inter, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '-0.02em',
        lineHeight: '1.5',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'japanese-zen',
    name: 'Kyoto Wabi-Sabi Residence',
    category: 'Minimal',
    description: 'Tranquil wabi-sabi charcoal stone with subtle bamboo and matcha accents.',
    mode: 'dark',
    tokens: {
      colors: {
        background: '#191919',
        foreground: '#e5e5e5',
        surface1: '#232323',
        surface2: '#2d2d2d',
        surface3: '#383838',
        card: '#232323',
        cardForeground: '#e5e5e5',
        primary: '#84cc16',
        primaryForeground: '#191919',
        secondary: '#a3a3a3',
        secondaryForeground: '#191919',
        accent: '#65a30d',
        accentForeground: '#ffffff',
        muted: '#2a2a2a',
        mutedForeground: '#a3a3a3',
        border: '#3a3a3a',
        focus: '#84cc16',
        success: '#84cc16',
        warning: '#eab308',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.125rem',
        radiusMd: '0.25rem',
        radiusLg: '0.375rem',
        radiusFull: '9999px',
        shadowPreset: 'none',
        shadowValue: 'none',
        containerMaxWidth: '1200px',
        spacingScale: '1.2rem',
      },
      typography: {
        headingFont: 'Outfit, sans-serif',
        bodyFont: 'DM Sans, sans-serif',
        uiFont: 'DM Sans, sans-serif',
        headingWeight: '500',
        bodyWeight: '300',
        letterSpacing: '0.03em',
        lineHeight: '1.7',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'cyberpunk-noir',
    name: 'Neo Shinjuku Skyline',
    category: 'High-Tech',
    description: 'Electric magenta neon glow with dark midnight indigo for forward-thinking smart towers.',
    mode: 'dark',
    tokens: {
      colors: {
        background: '#030712',
        foreground: '#f9fafb',
        surface1: '#111827',
        surface2: '#1f2937',
        surface3: '#374151',
        card: '#111827',
        cardForeground: '#f9fafb',
        primary: '#ec4899',
        primaryForeground: '#ffffff',
        secondary: '#06b6d4',
        secondaryForeground: '#030712',
        accent: '#a855f7',
        accentForeground: '#ffffff',
        muted: '#1f2937',
        mutedForeground: '#9ca3af',
        border: 'rgba(236, 72, 153, 0.3)',
        focus: '#ec4899',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
      },
      metrics: {
        radiusSm: '0.25rem',
        radiusMd: '0.375rem',
        radiusLg: '0.5rem',
        radiusFull: '9999px',
        shadowPreset: 'floating',
        shadowValue: '0 0 25px rgba(236, 72, 153, 0.25)',
        containerMaxWidth: '1360px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Space Grotesk, sans-serif',
        bodyFont: 'Inter, sans-serif',
        uiFont: 'Space Grotesk, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '-0.02em',
        lineHeight: '1.45',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'art-deco',
    name: 'Manhattan 1920s Art Deco',
    category: 'Artistic',
    description: 'Rich emerald green with brass geometric borders and roaring-twenties typography.',
    mode: 'dual',
    tokens: {
      colors: {
        background: '#042f2e',
        foreground: '#fef3c7',
        surface1: '#064e3b',
        surface2: '#065f46',
        surface3: '#047857',
        card: '#064e3b',
        cardForeground: '#fef3c7',
        primary: '#fbbf24',
        primaryForeground: '#042f2e',
        secondary: '#d97706',
        secondaryForeground: '#ffffff',
        accent: '#f59e0b',
        accentForeground: '#042f2e',
        muted: '#065f46',
        mutedForeground: '#fde68a',
        border: 'rgba(251, 191, 36, 0.35)',
        focus: '#fbbf24',
        success: '#34d399',
        warning: '#fbbf24',
        danger: '#f87171',
      },
      metrics: {
        radiusSm: '0px',
        radiusMd: '0.125rem',
        radiusLg: '0.25rem',
        radiusFull: '9999px',
        shadowPreset: 'dramatic',
        shadowValue: '0 20px 40px rgba(0, 0, 0, 0.6)',
        containerMaxWidth: '1240px',
        spacingScale: '1.05rem',
      },
      typography: {
        headingFont: 'Cinzel, serif',
        bodyFont: 'Montserrat, sans-serif',
        uiFont: 'Montserrat, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '0.05em',
        lineHeight: '1.6',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
  {
    key: 'desert-modern',
    name: 'Sonoran Desert Modernism',
    category: 'Warm',
    description: 'Palm Springs desert sand, adobe sunset tones, and crisp mid-century architecture.',
    mode: 'light',
    tokens: {
      colors: {
        background: '#fff7ed',
        foreground: '#431407',
        surface1: '#ffffff',
        surface2: '#ffedd5',
        surface3: '#fed7aa',
        card: '#ffffff',
        cardForeground: '#431407',
        primary: '#ea580c',
        primaryForeground: '#ffffff',
        secondary: '#15803d',
        secondaryForeground: '#ffffff',
        accent: '#d97706',
        accentForeground: '#ffffff',
        muted: '#ffedd5',
        mutedForeground: '#9a3412',
        border: '#fdba74',
        focus: '#ea580c',
        success: '#15803d',
        warning: '#ea580c',
        danger: '#b91c1c',
      },
      metrics: {
        radiusSm: '0.375rem',
        radiusMd: '0.75rem',
        radiusLg: '1.125rem',
        radiusFull: '9999px',
        shadowPreset: 'soft',
        shadowValue: '0 10px 30px -5px rgba(234, 88, 12, 0.08)',
        containerMaxWidth: '1280px',
        spacingScale: '1rem',
      },
      typography: {
        headingFont: 'Outfit, sans-serif',
        bodyFont: 'Plus Jakarta Sans, sans-serif',
        uiFont: 'Plus Jakarta Sans, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '-0.01em',
        lineHeight: '1.55',
      },
      motion: DEFAULT_DESIGN_TOKENS.motion,
    },
  },
];

export function getThemeByKey(key: string): ThemeDefinition {
  return SYSTEM_THEMES.find((t) => t.key === key) || SYSTEM_THEMES[0];
}
