import { PermissionDefinition } from '../types';

export const invoicePermissions: PermissionDefinition[] = [
  {
    key: 'invoice.list',
    module: 'invoices',
    label: 'List Invoices',
    description: 'Browse payment demands, milestone dues, and receipt records.',
    type: 'read',
    supportedScopes: ['own', 'assigned', 'all'],
    defaultScope: 'all',
  },
  {
    key: 'invoice.view',
    module: 'invoices',
    label: 'View Invoice Details',
    description: 'Inspect tax calculations, payment proofs, and audit timestamps.',
    type: 'read',
    supportedScopes: ['own', 'assigned', 'all'],
    defaultScope: 'all',
  },
  {
    key: 'invoice.download_pdf',
    module: 'invoices',
    label: 'Download Invoice PDF',
    description: 'Export official tax invoice and payment vouchers.',
    type: 'action',
    dependencies: ['invoice.view'],
  },
  {
    key: 'invoice.send_email',
    module: 'invoices',
    label: 'Email Invoice',
    description: 'Transmit payment request and receipt links directly to client email.',
    type: 'action',
    dependencies: ['invoice.view'],
  },
  {
    key: 'invoice.send_whatsapp',
    module: 'invoices',
    label: 'WhatsApp Invoice Link',
    description: 'Dispatch instant payment reminder and statement via WhatsApp gateway.',
    type: 'action',
    requiresFeature: 'whatsapp',
    dependencies: ['invoice.view'],
  },
  {
    key: 'invoice.record_payment',
    module: 'invoices',
    label: 'Record Payment',
    description: 'Log manual bank transfers, cheques, or POS confirmations.',
    type: 'action',
    dependencies: ['invoice.view'],
  },
  {
    key: 'invoice.void',
    module: 'invoices',
    label: 'Void / Cancel Invoice',
    description: 'Nullify an erroneous invoice with an obligatory audit rationale.',
    type: 'action',
    dangerous: true,
    dependencies: ['invoice.view'],
  },
];
