import { PermissionDefinition } from '../types';

export const leadPermissions: PermissionDefinition[] = [
  {
    key: 'lead.list',
    module: 'leads',
    label: 'List Leads',
    description: 'Browse inbound real estate inquiries and prospects.',
    type: 'read',
    supportedScopes: ['own', 'assigned', 'all'],
    defaultScope: 'assigned',
  },
  {
    key: 'lead.view',
    module: 'leads',
    label: 'View Lead Details',
    description: 'Read complete prospect inquiry details, contact info, and budget range.',
    type: 'read',
    supportedScopes: ['own', 'assigned', 'all'],
    defaultScope: 'assigned',
  },
  {
    key: 'lead.create',
    module: 'leads',
    label: 'Create Lead',
    description: 'Manually register a prospective buyer or phone inquiry into CRM.',
    type: 'write',
    dependencies: ['lead.view'],
  },
  {
    key: 'lead.edit',
    module: 'leads',
    label: 'Edit Lead',
    description: 'Update prospect status, notes, preferences, and qualification details.',
    type: 'write',
    supportedScopes: ['own', 'assigned', 'all'],
    defaultScope: 'assigned',
    dependencies: ['lead.view'],
  },
  {
    key: 'lead.assign',
    module: 'leads',
    label: 'Assign Lead',
    description: 'Reassign leads to other sales agents or team members.',
    type: 'action',
    supportedScopes: ['all'],
    dependencies: ['lead.view'],
  },
  {
    key: 'lead.convert_customer',
    module: 'leads',
    label: 'Convert to Customer',
    description: 'Promote qualified prospect to buyer account with portal credentials.',
    type: 'action',
    dependencies: ['lead.view'],
  },
  {
    key: 'lead.send_whatsapp',
    module: 'leads',
    label: 'Send WhatsApp Notification',
    description: 'Dispatch immediate WhatsApp conversation or brochure link to lead.',
    type: 'action',
    requiresFeature: 'whatsapp',
    dependencies: ['lead.view'],
  },
  {
    key: 'lead.send_email',
    module: 'leads',
    label: 'Send Email Communication',
    description: 'Send property brochures and schedule emails to leads.',
    type: 'action',
    dependencies: ['lead.view'],
  },
];
