import { PermissionDefinition } from '../types';

export const propertyPermissions: PermissionDefinition[] = [
  {
    key: 'property.list',
    module: 'properties',
    label: 'List Properties',
    description: 'View the directory and summaries of real estate developments and listings.',
    type: 'read',
    supportedScopes: ['own', 'assigned', 'all'],
    defaultScope: 'all',
  },
  {
    key: 'property.view',
    module: 'properties',
    label: 'View Property Details',
    description: 'Inspect full property specifications, 3D floorplans, and unit inventories.',
    type: 'read',
    supportedScopes: ['own', 'assigned', 'all'],
    defaultScope: 'all',
  },
  {
    key: 'property.create',
    module: 'properties',
    label: 'Create Property',
    description: 'Add new properties, configure 3D models, and define unit matrices.',
    type: 'write',
    dependencies: ['property.view'],
  },
  {
    key: 'property.edit',
    module: 'properties',
    label: 'Edit Property',
    description: 'Update property pricing, specifications, gallery assets, and availability.',
    type: 'write',
    supportedScopes: ['own', 'assigned', 'all'],
    defaultScope: 'all',
    dependencies: ['property.view'],
  },
  {
    key: 'property.archive',
    module: 'properties',
    label: 'Archive Property',
    description: 'Deactivate or unpublish properties from public visibility.',
    type: 'write',
    dangerous: true,
    dependencies: ['property.edit'],
  },
  {
    key: 'property.publish',
    module: 'properties',
    label: 'Publish Property',
    description: 'Make property listings publicly visible on the main website.',
    type: 'action',
    dependencies: ['property.edit'],
  },
  {
    key: 'property3d.view',
    module: 'properties',
    label: 'View 3D Experience',
    description: 'Access and preview 3D spatial models and walkthroughs in the dashboard.',
    type: 'read',
    supportedScopes: ['own', 'assigned', 'all'],
    defaultScope: 'all',
  },
  {
    key: 'property3d.upload',
    module: 'properties',
    label: 'Upload 3D Models',
    description: 'Upload new GLB 3D architectural models to properties.',
    type: 'write',
    dependencies: ['property3d.view'],
  },
  {
    key: 'property3d.edit',
    module: 'properties',
    label: 'Edit 3D Scene',
    description: 'Configure scene lighting, environment, camera, and hotspots.',
    type: 'write',
    dependencies: ['property3d.view'],
  },
  {
    key: 'property3d.map',
    module: 'properties',
    label: 'Map Floors and Units',
    description: 'Bind model scene-graph nodes to real database property floors and units.',
    type: 'write',
    dependencies: ['property3d.view', 'property3d.edit'],
  },
  {
    key: 'property3d.publish',
    module: 'properties',
    label: 'Publish 3D Experience',
    description: 'Publish draft 3D experiences to public property listings.',
    type: 'action',
    dependencies: ['property3d.view', 'property3d.edit'],
  },
  {
    key: 'property3d.rollback',
    module: 'properties',
    label: 'Rollback 3D Experience',
    description: 'Revert 3D experiences to previously published version snapshots.',
    type: 'action',
    dangerous: true,
    dependencies: ['property3d.publish'],
  },
];
